// SFSymbolCatalog.swift
// OSGKeyboard · Main App
//
// Generated from SF Symbols category metadata. Product-irrelevant categories
// are intentionally excluded to keep the skill icon picker focused and small.

enum SFSymbolCatalog {
    static let names: [String] = catalogText.split(whereSeparator: \.isNewline).map(String.init)

    private static let catalogText = """
1.calendar
1.lane
1.magnifyingglass
10.calendar
10.lane
11.calendar
11.lane
12.calendar
12.lane
123.rectangle
123.rectangle.fill
13.calendar
14.calendar
15.calendar
16.calendar
17.calendar
18.calendar
19.calendar
2.calendar
2.lane
20.calendar
21.calendar
22.calendar
23.calendar
24.calendar
25.calendar
26.calendar
27.calendar
28.calendar
29.calendar
3.calendar
3.lane
30.calendar
31.calendar
4.calendar
4.lane
5.calendar
5.lane
6.calendar
6.lane
7.calendar
7.lane
8.calendar
8.lane
9.calendar
9.lane
a
a.book.closed
a.book.closed.fill
a.magnify
abc
ac
ac.slash
accessibility.badge.arrow.up.right
accessibility.fill
air.conditioner.horizontal
air.conditioner.horizontal.fill
air.conditioner.vertical
air.conditioner.vertical.fill
air.purifier
air.purifier.fill
airplane
airplane.arrival
airplane.circle.fill
airplane.cloud
airplane.departure
airplane.landed
airplane.path.dotted
airplane.ticket
airplane.ticket.fill
airplane.up.forward
airplane.up.forward.app
airplane.up.forward.app.fill
airplane.up.right
airplane.up.right.app
airplane.up.right.app.fill
airplaneseat
airplay.video
airplay.video.badge.exclamationmark
airplay.video.circle.fill
airplayaudio
airplayaudio.badge.exclamationmark
airplayaudio.circle
airplayaudio.circle.fill
airplayvideo
airplayvideo.badge.exclamationmark
airplayvideo.circle
airplayvideo.circle.fill
airpodpro.left
airpodpro.right
airpodsmax
airpodspro
airpodspro.chargingcase.wireless
airpodspro.chargingcase.wireless.fill
airpodspro.chargingcase.wireless.radiowaves.left.and.right
airpodspro.chargingcase.wireless.radiowaves.left.and.right.fill
alarm
alarm.fill
align.horizontal.center
align.horizontal.center.fill
align.horizontal.left
align.horizontal.left.fill
align.horizontal.right
align.horizontal.right.fill
align.vertical.bottom
align.vertical.bottom.fill
align.vertical.center
align.vertical.center.fill
align.vertical.top
align.vertical.top.fill
allergens
allergens.fill
alternatingcurrent
american.football
american.football.circle.fill
american.football.fill
american.football.professional
american.football.professional.circle.fill
american.football.professional.fill
amplifier
ant
ant.circle.fill
ant.fill
antenna.radiowaves.left.and.right.slash
antenna.radiowaves.left.and.right.slash.circle.fill
app.background.dotted
app.badge
app.badge.checkmark
app.badge.checkmark.fill
app.badge.clock
app.badge.clock.fill
app.badge.fill
app.connected.to.app.below.fill
app.dashed
app.gift
app.gift.fill
app.grid
app.shadow
app.specular
app.translucent
appclip
append.page
append.page.fill
apple.books.pages
apple.books.pages.fill
apple.classical.pages
apple.classical.pages.fill
apple.haptics.and.exclamationmark.triangle
apple.haptics.and.music.note
apple.haptics.and.music.note.slash
apple.image.playground
apple.image.playground.fill
apple.intelligence
apple.intelligence.badge.xmark
apple.logo
apple.meditate
apple.meditate.circle.fill
apple.meditate.square.stack
apple.meditate.square.stack.fill
apple.podcasts.pages
apple.podcasts.pages.fill
apple.terminal
apple.terminal.circle.fill
apple.terminal.fill
apple.terminal.on.rectangle
apple.terminal.on.rectangle.fill
apple.writing.tools
applelogo
applescript
applescript.fill
applewatch.case.inset.filled
appwindow.swipe.rectangle
arcade.stick
arcade.stick.and.arrow.down
arcade.stick.and.arrow.left
arcade.stick.and.arrow.left.and.arrow.right
arcade.stick.and.arrow.left.and.arrow.right.outward
arcade.stick.and.arrow.right
arcade.stick.and.arrow.up
arcade.stick.and.arrow.up.and.arrow.down
archivebox
archivebox.circle.fill
archivebox.fill
arkit
arkit.badge.xmark
arrow.2.circlepath
arrow.2.circlepath.circle
arrow.2.circlepath.circle.fill
arrow.branch
arrow.circlepath
arrow.clockwise.heart
arrow.clockwise.heart.fill
arrow.clockwise.icloud
arrow.clockwise.icloud.fill
arrow.counterclockwise.icloud
arrow.counterclockwise.icloud.fill
arrow.down.app.dashed
arrow.down.app.dashed.trianglebadge.exclamationmark
arrow.down.doc
arrow.down.doc.fill
arrow.down.document
arrow.down.document.fill
arrow.down.left.video
arrow.down.left.video.fill
arrow.down.message
arrow.down.message.fill
arrow.down.to.line.alt
arrow.forward.folder
arrow.forward.folder.fill
arrow.left.and.right.righttriangle.left.righttriangle.right
arrow.left.and.right.righttriangle.left.righttriangle.right.fill
arrow.left.to.line.alt
arrow.merge
arrow.rectanglepath
arrow.right.arrow.left
arrow.right.arrow.left.circle
arrow.right.arrow.left.circle.fill
arrow.right.arrow.left.square
arrow.right.arrow.left.square.fill
arrow.right.doc.on.clipboard
arrow.right.page.on.clipboard
arrow.right.to.line.alt
arrow.swap
arrow.triangle.2.circlepath
arrow.triangle.2.circlepath.camera
arrow.triangle.2.circlepath.camera.fill
arrow.triangle.2.circlepath.circle
arrow.triangle.2.circlepath.circle.fill
arrow.triangle.2.circlepath.doc.on.clipboard
arrow.triangle.2.circlepath.icloud
arrow.triangle.2.circlepath.icloud.fill
arrow.triangle.branch
arrow.triangle.capsulepath
arrow.triangle.merge
arrow.triangle.pull
arrow.triangle.swap
arrow.triangle.turn.up.right.circle
arrow.triangle.turn.up.right.circle.fill
arrow.triangle.turn.up.right.diamond
arrow.triangle.turn.up.right.diamond.fill
arrow.trianglehead.2.clockwise.rotate.90.camera
arrow.trianglehead.2.clockwise.rotate.90.camera.fill
arrow.trianglehead.2.clockwise.rotate.90.icloud
arrow.trianglehead.2.clockwise.rotate.90.icloud.fill
arrow.trianglehead.2.clockwise.rotate.90.page.on.clipboard
arrow.trianglehead.clockwise.icloud
arrow.trianglehead.clockwise.icloud.fill
arrow.trianglehead.counterclockwise.icloud
arrow.trianglehead.counterclockwise.icloud.fill
arrow.trianglehead.left.and.right.righttriangle.left.righttriangle.right
arrow.trianglehead.left.and.right.righttriangle.left.righttriangle.right.fill
arrow.trianglehead.up.and.down.righttriangle.up.righttriangle.down
arrow.trianglehead.up.and.down.righttriangle.up.righttriangle.down.fill
arrow.up.and.down.righttriangle.up.fill.righttriangle.down.fill
arrow.up.and.down.righttriangle.up.righttriangle.down
arrow.up.and.down.righttriangle.up.righttriangle.down.fill
arrow.up.and.person.rectangle.portrait
arrow.up.and.person.rectangle.turn.left
arrow.up.and.person.rectangle.turn.right
arrow.up.bin
arrow.up.bin.fill
arrow.up.doc
arrow.up.doc.fill
arrow.up.doc.on.clipboard
arrow.up.document
arrow.up.document.fill
arrow.up.folder
arrow.up.folder.fill
arrow.up.left.and.down.right.magnifyingglass
arrow.up.message
arrow.up.message.fill
arrow.up.page.on.clipboard
arrow.up.right.diamond
arrow.up.right.diamond.fill
arrow.up.right.video
arrow.up.right.video.fill
arrow.up.to.line.alt
arrow.up.trash
arrow.up.trash.fill
arrowkeys
arrowkeys.down.filled
arrowkeys.fill
arrowkeys.left.filled
arrowkeys.right.filled
arrowkeys.up.filled
arrowtriangle.backward.inset.filled.trailingthird.rectangle
arrowtriangle.forward.inset.filled.trailingthird.rectangle
arrowtriangle.left.fill.and.line.vertical.and.arrowtriangle.right.fill
arrowtriangle.right.fill.and.line.vertical.and.arrowtriangle.left.fill
aspectratio
aspectratio.fill
asterisk
asterisk.circle.fill
at
at.badge.minus
at.badge.plus
at.circle.fill
atom
australian.football
australian.football.circle.fill
australian.football.fill
australiandollarsign.arrow.circlepath
australiandollarsign.bank.building
australiandollarsign.bank.building.fill
australsign.arrow.circlepath
australsign.bank.building
australsign.bank.building.fill
auto.brakesignal
auto.headlight.high.beam
auto.headlight.high.beam.fill
auto.headlight.low.beam
auto.headlight.low.beam.fill
axel.2
axel.2.front.and.rear.engaged
axel.2.front.engaged
axel.2.rear.engaged
backpack
backpack.circle.fill
backpack.fill
bahtsign.arrow.circlepath
bahtsign.bank.building
bahtsign.bank.building.fill
balloon
balloon.2
balloon.2.fill
balloon.fill
bandage
bandage.fill
barcode
barcode.viewfinder
barometer
base.unit
baseball
baseball.circle.fill
baseball.diamond.bases
baseball.diamond.bases.outs.indicator
baseball.fill
basketball
basketball.circle.fill
basketball.fill
bathtub
bathtub.fill
battery.0
battery.0percent
battery.100
battery.100.bolt
battery.100.circle
battery.100.circle.fill
battery.100percent
battery.100percent.bolt
battery.100percent.circle.fill
battery.25
battery.25percent
battery.50
battery.50percent
battery.75
battery.75percent
beach.umbrella
beach.umbrella.fill
beats.fit.pro
beats.fit.pro.chargingcase
beats.fit.pro.chargingcase.fill
beats.fit.pro.left
beats.fit.pro.right
beats.powerbeatspro
beats.powerbeatspro.chargingcase
beats.powerbeatspro.chargingcase.fill
beats.powerbeatspro.left
beats.powerbeatspro.right
beats.studiobud.left
beats.studiobud.right
beats.studiobudsplus
beats.studiobudsplus.chargingcase
beats.studiobudsplus.chargingcase.fill
beats.studiobudsplus.left
beats.studiobudsplus.right
bed.double
bed.double.badge.checkmark
bed.double.badge.checkmark.fill
bed.double.circle.fill
bed.double.fill
bell
bell.and.waveform
bell.and.waveform.fill
bell.badge
bell.badge.circle.fill
bell.badge.fill
bell.badge.slash
bell.badge.slash.fill
bell.badge.waveform.slash
bell.badge.waveform.slash.fill
bell.circle.fill
bell.fill
bell.slash
bell.slash.circle.fill
bell.slash.fill
bell.square
bell.square.fill
beziercurve
bicycle
bicycle.circle.fill
bin.xmark
bin.xmark.fill
binoculars
binoculars.circle.fill
binoculars.fill
bird
bird.circle.fill
bird.fill
birthday.cake
birthday.cake.fill
bitcoinsign.arrow.circlepath
bitcoinsign.bank.building
bitcoinsign.bank.building.fill
blinds.horizontal.closed
blinds.horizontal.open
blinds.vertical.closed
blinds.vertical.open
blood.pressure.cuff
blood.pressure.cuff.badge.gauge.with.needle
blood.pressure.cuff.badge.gauge.with.needle.fill
blood.pressure.cuff.fill
bolt
bolt.badge.a
bolt.badge.a.fill
bolt.badge.automatic
bolt.badge.automatic.fill
bolt.badge.checkmark
bolt.badge.checkmark.fill
bolt.badge.clock
bolt.badge.clock.fill
bolt.badge.xmark
bolt.badge.xmark.fill
bolt.circle.fill
bolt.fill
bolt.fill.batteryblock
bolt.fill.batteryblock.fill
bolt.heart.fill
bolt.horizontal
bolt.horizontal.circle.fill
bolt.horizontal.fill
bolt.horizontal.icloud
bolt.horizontal.icloud.fill
bolt.house
bolt.house.fill
bolt.ring.closed
bolt.shield
bolt.shield.fill
bolt.slash
bolt.slash.circle.fill
bolt.slash.fill
bolt.square
bolt.square.fill
bolt.trianglebadge.exclamationmark
bolt.trianglebadge.exclamationmark.fill
bonjour
book
book.badge.plus
book.badge.plus.fill
book.circle.fill
book.closed
book.closed.circle.fill
book.closed.fill
book.fill
book.pages
book.pages.fill
bookmark
bookmark.circle.fill
bookmark.fill
bookmark.slash
bookmark.slash.fill
bookmark.square
bookmark.square.fill
books.vertical
books.vertical.circle.fill
books.vertical.fill
box.truck
box.truck.badge.clock
box.truck.badge.clock.fill
box.truck.fill
brain
brain.fill
brain.filled.head.profile
brain.head.profile
brain.head.profile.fill
brazilianrealsign.arrow.circlepath
brazilianrealsign.bank.building
brazilianrealsign.bank.building.fill
briefcase
briefcase.circle.fill
briefcase.fill
bubble
bubble.and.pencil
bubble.circle.fill
bubble.fill
bubble.left
bubble.left.and.bubble.right
bubble.left.and.bubble.right.fill
bubble.left.and.exclamationmark.bubble.right
bubble.left.and.exclamationmark.bubble.right.fill
bubble.left.and.text.bubble.right
bubble.left.and.text.bubble.right.fill
bubble.left.circle.fill
bubble.left.fill
bubble.middle.bottom
bubble.middle.bottom.fill
bubble.middle.top
bubble.middle.top.fill
bubble.right
bubble.right.circle.fill
bubble.right.fill
bubbles.and.sparkles
bubbles.and.sparkles.fill
building
building.2
building.2.crop.circle
building.2.crop.circle.fill
building.2.fill
building.columns
building.columns.circle
building.columns.circle.fill
building.columns.fill
building.fill
burn
burst
burst.fill
bus
bus.doubledecker
bus.doubledecker.fill
bus.fill
button.programmable
button.programmable.square
button.programmable.square.fill
cabinet
cabinet.fill
cablecar
cablecar.fill
calendar
calendar.and.person
calendar.badge
calendar.badge.checkmark
calendar.badge.clock
calendar.badge.exclamationmark
calendar.badge.lock
calendar.badge.minus
calendar.badge.plus
calendar.circle.fill
calendar.day.timeline.leading
calendar.day.timeline.leading.circle.fill
calendar.day.timeline.left
calendar.day.timeline.left.circle.fill
calendar.day.timeline.right
calendar.day.timeline.right.circle.fill
calendar.day.timeline.trailing
calendar.day.timeline.trailing.circle.fill
camera
camera.aperture
camera.badge.clock
camera.badge.clock.fill
camera.badge.ellipsis
camera.badge.ellipsis.fill
camera.circle.fill
camera.fill
camera.fill.badge.ellipsis
camera.filters
camera.macro
camera.macro.circle.fill
camera.macro.slash
camera.macro.slash.circle.fill
camera.metering.center.weighted.average
camera.metering.none
camera.metering.partial
camera.metering.spot
camera.metering.unknown
camera.on.rectangle
camera.on.rectangle.fill
camera.rotate
camera.rotate.fill
camera.shutter.button
camera.shutter.button.fill
camera.viewfinder
camera.viewfinder.badge.automatic
capsule.bottomhalf.filled
capsule.inset.filled
capsule.lefthalf.filled
capsule.on.capsule
capsule.on.capsule.fill
capsule.on.rectangle
capsule.on.rectangle.fill
capsule.portrait.bottomhalf.filled
capsule.portrait.inset.filled
capsule.portrait.lefthalf.filled
capsule.portrait.righthalf.filled
capsule.portrait.tophalf.filled
capsule.righthalf.filled
capsule.tophalf.filled
captions.bubble
captions.bubble.fill
car.ferry
car.ferry.fill
car.top.frontleft.arrowtriangle
car.top.frontleft.arrowtriangle.fill
car.top.frontright.arrowtriangle
car.top.frontright.arrowtriangle.fill
car.top.rearleft.arrowtriangle
car.top.rearleft.arrowtriangle.fill
car.top.rearright.arrowtriangle
car.top.rearright.arrowtriangle.fill
carbon.dioxide.cloud
carbon.dioxide.cloud.fill
carbon.monoxide.cloud
carbon.monoxide.cloud.fill
carrot
carrot.fill
case
case.fill
cat
cat.circle.fill
cat.fill
cedisign.arrow.circlepath
cedisign.bank.building
cedisign.bank.building.fill
centsign.arrow.circlepath
centsign.bank.building
centsign.bank.building.fill
chair
chair.fill
chair.lounge
chair.lounge.fill
chandelier
chandelier.fill
character.book.closed
character.book.closed.bn
character.book.closed.fill
character.book.closed.fill.bn
character.book.closed.fill.gu
character.book.closed.fill.kn
character.book.closed.fill.ml
character.book.closed.fill.mni
character.book.closed.fill.mr
character.book.closed.fill.or
character.book.closed.fill.pa
character.book.closed.fill.sat
character.book.closed.fill.si
character.book.closed.fill.ta
character.book.closed.fill.te
character.book.closed.gu
character.book.closed.kn
character.book.closed.ml
character.book.closed.mni
character.book.closed.mr
character.book.closed.or
character.book.closed.pa
character.book.closed.sat
character.book.closed.si
character.book.closed.ta
character.book.closed.te
character.bubble
character.bubble.bn
character.bubble.fill
character.bubble.fill.bn
character.bubble.fill.gu
character.bubble.fill.kn
character.bubble.fill.ml
character.bubble.fill.mni
character.bubble.fill.mr
character.bubble.fill.or
character.bubble.fill.pa
character.bubble.fill.sat
character.bubble.fill.si
character.bubble.fill.ta
character.bubble.fill.te
character.bubble.gu
character.bubble.kn
character.bubble.ml
character.bubble.mni
character.bubble.mr
character.bubble.or
character.bubble.pa
character.bubble.sat
character.bubble.si
character.bubble.ta
character.bubble.te
character.cursor.ibeam.bn
character.cursor.ibeam.gu
character.cursor.ibeam.kn
character.cursor.ibeam.ml
character.cursor.ibeam.mni
character.cursor.ibeam.mr
character.cursor.ibeam.or
character.cursor.ibeam.pa
character.cursor.ibeam.sat
character.cursor.ibeam.si
character.cursor.ibeam.ta
character.cursor.ibeam.te
character.text.justify.te
chart.bar.doc.horizontal
chart.bar.doc.horizontal.fill
chart.line.downtrend.xyaxis
chart.line.downtrend.xyaxis.circle.fill
chart.line.flattrend.xyaxis
chart.line.flattrend.xyaxis.circle.fill
chart.line.text.clipboard
chart.line.text.clipboard.fill
chart.line.uptrend.xyaxis
chart.line.uptrend.xyaxis.circle.fill
chart.pie
chart.pie.fill
chart.xyaxis.line
checkerboard.rectangle
checkerboard.shield
checkmark
checkmark.app
checkmark.app.fill
checkmark.arrow.trianglehead.clockwise
checkmark.bubble
checkmark.bubble.fill
checkmark.circle.badge.airplane
checkmark.circle.badge.airplane.fill
checkmark.circle.badge.plus.fill
checkmark.circle.badge.questionmark.fill
checkmark.circle.badge.xmark.fill
checkmark.circle.dotted
checkmark.circle.fill
checkmark.circle.trianglebadge.exclamationmark.fill
checkmark.diamond
checkmark.diamond.fill
checkmark.gobackward
checkmark.icloud
checkmark.icloud.fill
checkmark.message
checkmark.message.fill
checkmark.rectangle
checkmark.rectangle.fill
checkmark.rectangle.portrait
checkmark.rectangle.portrait.fill
checkmark.rectangle.stack
checkmark.rectangle.stack.fill
checkmark.seal
checkmark.seal.fill
checkmark.seal.text.page
checkmark.seal.text.page.fill
checkmark.shield
checkmark.shield.fill
checkmark.square
checkmark.square.fill
chevron.left.forwardslash.chevron.right
chevron.left.slash.chevron.right
chineseyuanrenminbisign.arrow.circlepath
chineseyuanrenminbisign.bank.building
chineseyuanrenminbisign.bank.building.fill
circle.and.line.horizontal
circle.and.line.horizontal.fill
circle.badge.checkmark.fill
circle.badge.exclamationmark.fill
circle.badge.minus.fill
circle.badge.plus.fill
circle.badge.questionmark.fill
circle.badge.xmark.fill
circle.bottomhalf.fill
circle.bottomhalf.filled
circle.bottomhalf.filled.inverse
circle.bottomrighthalf.checkered
circle.bottomrighthalf.pattern.checkered
circle.bottomthird.split
circle.circle.fill
circle.dashed
circle.dashed.inset.fill
circle.dashed.inset.filled
circle.dashed.rectangle
circle.dotted
circle.dotted.and.circle
circle.dotted.circle.fill
circle.fill.square.fill
circle.filled.pattern.diagonalline.rectangle
circle.grid.2x1
circle.grid.2x1.fill
circle.grid.2x1.left.filled
circle.grid.2x1.right.filled
circle.grid.2x2
circle.grid.2x2.fill
circle.grid.2x2.topleft.checkmark.filled
circle.grid.3x3
circle.grid.3x3.circle.fill
circle.grid.3x3.fill
circle.grid.cross
circle.grid.cross.down.fill
circle.grid.cross.down.filled
circle.grid.cross.fill
circle.grid.cross.left.fill
circle.grid.cross.left.filled
circle.grid.cross.right.fill
circle.grid.cross.right.filled
circle.grid.cross.up.fill
circle.grid.cross.up.filled
circle.grid.hex
circle.grid.hex.fill
circle.hexagongrid
circle.hexagongrid.circle.fill
circle.hexagongrid.fill
circle.hexagonpath
circle.hexagonpath.fill
circle.inset.filled
circle.lefthalf.fill
circle.lefthalf.filled
circle.lefthalf.filled.inverse
circle.lefthalf.filled.righthalf.striped.horizontal
circle.lefthalf.filled.righthalf.striped.horizontal.inverse
circle.lefthalf.striped.horizontal
circle.lefthalf.striped.horizontal.inverse
circle.on.square
circle.on.square.intersection.dotted
circle.on.square.merge
circle.rectangle.dashed
circle.rectangle.filled.pattern.diagonalline
circle.righthalf.fill
circle.righthalf.filled
circle.righthalf.filled.inverse
circle.slash
circle.slash.fill
circle.square
circle.square.fill
circle.tophalf.fill
circle.tophalf.filled
circle.tophalf.filled.inverse
circlebadge
circlebadge.2
circlebadge.2.fill
circlebadge.fill
circles.hexagongrid
circles.hexagongrid.fill
circles.hexagonpath
circles.hexagonpath.fill
clipboard
clipboard.fill
clock
clock.arrow.2.circlepath
clock.arrow.circlepath
clock.arrow.trianglehead.clockwise.rotate.90.path.dotted
clock.badge
clock.badge.airplane
clock.badge.airplane.fill
clock.badge.checkmark
clock.badge.checkmark.fill
clock.badge.exclamationmark
clock.badge.exclamationmark.fill
clock.badge.fill
clock.badge.questionmark
clock.badge.questionmark.fill
clock.badge.xmark
clock.badge.xmark.fill
clock.circle.fill
clock.fill
cloud
cloud.bolt
cloud.bolt.circle.fill
cloud.bolt.fill
cloud.bolt.rain
cloud.bolt.rain.circle.fill
cloud.bolt.rain.fill
cloud.circle.fill
cloud.drizzle
cloud.drizzle.circle.fill
cloud.drizzle.fill
cloud.fill
cloud.fog
cloud.fog.circle.fill
cloud.fog.fill
cloud.hail
cloud.hail.circle.fill
cloud.hail.fill
cloud.heavyrain
cloud.heavyrain.circle.fill
cloud.heavyrain.fill
cloud.moon
cloud.moon.bolt
cloud.moon.bolt.circle.fill
cloud.moon.bolt.fill
cloud.moon.circle.fill
cloud.moon.fill
cloud.moon.rain
cloud.moon.rain.circle.fill
cloud.moon.rain.fill
cloud.rain
cloud.rain.circle.fill
cloud.rain.fill
cloud.rainbow.half
cloud.rainbow.half.fill
cloud.sleet
cloud.sleet.circle.fill
cloud.sleet.fill
cloud.snow
cloud.snow.circle.fill
cloud.snow.fill
cloud.sun
cloud.sun.bolt
cloud.sun.bolt.circle.fill
cloud.sun.bolt.fill
cloud.sun.circle.fill
cloud.sun.fill
cloud.sun.rain
cloud.sun.rain.circle.fill
cloud.sun.rain.fill
coat
coat.circle.fill
coat.fill
coloncurrencysign.arrow.circlepath
coloncurrencysign.bank.building
coloncurrencysign.bank.building.fill
comb
comb.fill
cone
cone.fill
contact.sensor
contact.sensor.fill
contextualmenu.and.cursorarrow
contextualmenu.and.pointer.arrow
cooktop
cooktop.fill
cpu
cpu.fill
creditcard.and.123
creditcard.viewfinder
cricket.ball
cricket.ball.circle.fill
cricket.ball.fill
crop
crop.rotate
cross
cross.case
cross.case.circle.fill
cross.case.fill
cross.circle.fill
cross.fill
cross.vial
cross.vial.fill
crown
crown.fill
cruzeirosign.arrow.circlepath
cruzeirosign.bank.building
cruzeirosign.bank.building.fill
cube
cube.box
cube.box.fill
cube.circle.fill
cube.fill
cube.transparent
cube.transparent.fill
cup.and.heat.waves
cup.and.heat.waves.fill
cup.and.saucer
cup.and.saucer.fill
curlybraces
curlybraces.square
curlybraces.square.fill
cursor.rays
cursorarrow
cursorarrow.and.square.on.square.dashed
cursorarrow.click
cursorarrow.click.2
cursorarrow.click.badge.clock
cursorarrow.motionlines
cursorarrow.motionlines.click
cursorarrow.rays
cursorarrow.resize.north.east.south.east
cursorarrow.slash
cursorarrow.slash.square
cursorarrow.slash.square.fill
cursorarrow.square
cursorarrow.square.fill
curtains.closed
curtains.open
cylinder
cylinder.fill
cylinder.split.1x2
cylinder.split.1x2.fill
danishkronesign.arrow.circlepath
danishkronesign.bank.building
danishkronesign.bank.building.fill
degreesign.celsius
degreesign.fahrenheit
dehumidifier
dehumidifier.fill
deskclock
deskclock.fill
deskview
deskview.fill
dial
dial.fill
dial.high
dial.high.fill
dial.low
dial.low.fill
dial.max
dial.max.fill
dial.medium
dial.medium.fill
dial.min
dial.min.fill
diamond.bottomhalf.filled
diamond.circle.fill
diamond.inset.filled
diamond.lefthalf.filled
diamond.righthalf.filled
diamond.tophalf.filled
dice
dice.fill
die.face.1
die.face.1.fill
die.face.2
die.face.2.fill
die.face.3
die.face.3.fill
die.face.4
die.face.4.fill
die.face.5
die.face.5.fill
die.face.6
die.face.6.fill
directcurrent
dishwasher
dishwasher.circle.fill
dishwasher.fill
distribute.horizontal
distribute.horizontal.center
distribute.horizontal.center.fill
distribute.horizontal.fill
distribute.horizontal.left
distribute.horizontal.left.fill
distribute.horizontal.right
distribute.horizontal.right.fill
distribute.vertical
distribute.vertical.bottom
distribute.vertical.bottom.fill
distribute.vertical.center
distribute.vertical.center.fill
distribute.vertical.fill
distribute.vertical.top
distribute.vertical.top.fill
doc
doc.append
doc.append.fill
doc.badge.arrow.up
doc.badge.arrow.up.fill
doc.badge.clock
doc.badge.clock.fill
doc.badge.ellipsis
doc.badge.gearshape
doc.badge.gearshape.fill
doc.badge.plus
doc.circle
doc.circle.fill
doc.fill
doc.fill.badge.ellipsis
doc.fill.badge.plus
doc.on.clipboard
doc.on.clipboard.fill
doc.on.doc
doc.on.doc.fill
doc.plaintext
doc.plaintext.fill
doc.questionmark
doc.questionmark.fill
doc.richtext
doc.richtext.fill
doc.text
doc.text.below.ecg
doc.text.below.ecg.fill
doc.text.fill
doc.text.fill.viewfinder
doc.text.image
doc.text.image.fill
doc.text.magnifyingglass
doc.text.viewfinder
doc.viewfinder
doc.viewfinder.fill
doc.zipper
dock.arrow.down.rectangle
dock.arrow.up.rectangle
dock.rectangle
document
document.badge.arrow.up
document.badge.arrow.up.fill
document.badge.clock
document.badge.clock.fill
document.badge.ellipsis
document.badge.ellipsis.fill
document.badge.gearshape
document.badge.gearshape.fill
document.badge.plus
document.badge.plus.fill
document.circle.fill
document.fill
document.on.clipboard
document.on.clipboard.fill
document.on.document
document.on.document.fill
document.on.trash
document.on.trash.fill
document.viewfinder
document.viewfinder.fill
dog
dog.circle.fill
dog.fill
dollarsign.arrow.circlepath
dollarsign.bank.building
dollarsign.bank.building.fill
dongsign.arrow.circlepath
dongsign.bank.building
dongsign.bank.building.fill
door.french.closed
door.french.open
door.garage.closed
door.garage.closed.trianglebadge.exclamationmark
door.garage.double.bay.closed
door.garage.double.bay.closed.trianglebadge.exclamationmark
door.garage.double.bay.open
door.garage.double.bay.open.trianglebadge.exclamationmark
door.garage.open
door.garage.open.trianglebadge.exclamationmark
door.left.hand.closed
door.left.hand.open
door.right.hand.closed
door.right.hand.open
door.sliding.left.hand.closed
door.sliding.left.hand.open
door.sliding.right.hand.closed
door.sliding.right.hand.open
dot.circle.and.cursorarrow
dot.circle.and.hand.point.up.left.fill
dot.circle.and.pointer.arrow
dot.circle.viewfinder
dot.crosshair
dot.scope
dot.square
dot.square.fill
dot.squareshape
dot.squareshape.fill
dot.squareshape.split.2x2
dot.viewfinder
dots.and.line.vertical.and.cursorarrow.rectangle
dots.and.line.vertical.and.pointer.arrow.rectangle
dpad
dpad.down.fill
dpad.down.filled
dpad.fill
dpad.left.fill
dpad.left.filled
dpad.right.fill
dpad.right.filled
dpad.up.fill
dpad.up.filled
drone
drone.fill
drop
drop.circle.fill
drop.degreesign
drop.degreesign.fill
drop.degreesign.slash
drop.degreesign.slash.fill
drop.fill
drop.halffull
drop.keypad.rectangle
drop.keypad.rectangle.fill
drop.triangle
drop.triangle.fill
dryer
dryer.circle.fill
dryer.fill
duffle.bag
duffle.bag.fill
dumbbell
dumbbell.fill
ear
ear.and.waveform
ear.badge.checkmark
ear.fill
ear.trianglebadge.exclamationmark
ecg.text.page
ecg.text.page.fill
ellipses.bubble
ellipses.bubble.fill
entry.lever.keypad
entry.lever.keypad.fill
entry.lever.keypad.trianglebadge.exclamationmark
entry.lever.keypad.trianglebadge.exclamationmark.fill
envelope
envelope.and.arrow.3.down
envelope.and.arrow.3.down.fill
envelope.and.arrow.trianglehead.branch
envelope.and.arrow.trianglehead.branch.fill
envelope.and.hand.raised
envelope.and.hand.raised.fill
envelope.arrow.triangle.branch
envelope.arrow.triangle.branch.fill
envelope.badge
envelope.badge.fill
envelope.badge.minus
envelope.badge.minus.fill
envelope.badge.person.crop
envelope.badge.person.crop.fill
envelope.badge.plus
envelope.badge.plus.fill
envelope.badge.shield.half.filled
envelope.badge.shield.half.filled.fill
envelope.badge.shield.leadinghalf.fill
envelope.circle.fill
envelope.fill
envelope.fill.badge.shield.trailinghalf.fill
envelope.front
envelope.front.fill
envelope.open
envelope.open.badge.clock
envelope.open.badge.clock.fill
envelope.open.fill
envelope.stack
envelope.stack.fill
environments
environments.circle.fill
environments.fill
environments.slash
environments.slash.circle.fill
environments.slash.fill
eraser
eraser.badge.xmark
eraser.badge.xmark.fill
eraser.fill
eraser.line.dashed
eraser.line.dashed.fill
eraser.slash
eraser.slash.fill
eraser.trianglebadge.exclamationmark
eraser.trianglebadge.exclamationmark.fill
esim
esim.fill
eurosign.arrow.circlepath
eurosign.bank.building
eurosign.bank.building.fill
eurozonesign.arrow.circlepath
eurozonesign.bank.building
eurozonesign.bank.building.fill
exclamationmark
exclamationmark.2
exclamationmark.3
exclamationmark.arrow.circlepath
exclamationmark.arrow.triangle.2.circlepath
exclamationmark.bubble
exclamationmark.bubble.circle.fill
exclamationmark.bubble.fill
exclamationmark.icloud
exclamationmark.icloud.fill
exclamationmark.lock
exclamationmark.lock.fill
exclamationmark.magnifyingglass
exclamationmark.message
exclamationmark.message.fill
exclamationmark.octagon
exclamationmark.octagon.fill
exclamationmark.questionmark
exclamationmark.shield
exclamationmark.shield.fill
exclamationmark.triangle.text.page
exclamationmark.triangle.text.page.fill
externaldrive
externaldrive.badge.checkmark
externaldrive.badge.exclamationmark
externaldrive.badge.icloud
externaldrive.badge.minus
externaldrive.badge.person.crop
externaldrive.badge.plus
externaldrive.badge.questionmark
externaldrive.badge.timemachine
externaldrive.badge.xmark
externaldrive.connected.to.line.below
externaldrive.connected.to.line.below.fill
externaldrive.fill
externaldrive.fill.badge.checkmark
externaldrive.fill.badge.exclamationmark
externaldrive.fill.badge.icloud
externaldrive.fill.badge.minus
externaldrive.fill.badge.person.crop
externaldrive.fill.badge.plus
externaldrive.fill.badge.questionmark
externaldrive.fill.badge.timemachine
externaldrive.fill.badge.xmark
externaldrive.fill.trianglebadge.exclamationmark
externaldrive.trianglebadge.exclamationmark
eye
eye.circle.fill
eye.fill
eye.half.closed
eye.half.closed.fill
eye.slash
eye.slash.circle.fill
eye.slash.fill
eye.square
eye.square.fill
eye.trianglebadge.exclamationmark
eye.trianglebadge.exclamationmark.fill
eyebrow
eyedropper
eyedropper.full
eyedropper.halffull
eyeglasses
eyeglasses.slash
eyes
eyes.inverse
f.cursive
f.cursive.circle.fill
f.cursive.slash
face.dashed
face.dashed.fill
face.smiling
face.smiling.fill
face.smiling.inverse
faceid
facemask
facemask.fill
fan.and.light.ceiling
fan.and.light.ceiling.fill
fan.ceiling
fan.ceiling.fill
fan.desk
fan.desk.fill
fan.floor
fan.floor.fill
fan.oscillation
fan.oscillation.fill
fanblades
fanblades.fill
fanblades.slash
fanblades.slash.fill
ferry
ferry.fill
fiberchannel
fibrechannel
field.of.view.ultrawide
field.of.view.ultrawide.fill
field.of.view.wide
field.of.view.wide.fill
figure
figure.2
figure.2.and.child.holdinghands
figure.2.arms.open
figure.2.circle.fill
figure.2.left.holdinghands
figure.2.right.holdinghands
figure.american.football
figure.american.football.circle.fill
figure.and.child.holdinghands
figure.archery
figure.archery.circle.fill
figure.arms.open
figure.australian.football
figure.australian.football.circle.fill
figure.badminton
figure.badminton.circle.fill
figure.barre
figure.barre.circle.fill
figure.baseball
figure.baseball.circle.fill
figure.basketball
figure.basketball.circle.fill
figure.bowling
figure.bowling.circle.fill
figure.boxing
figure.boxing.circle.fill
figure.climbing
figure.climbing.circle.fill
figure.cooldown
figure.cooldown.circle.fill
figure.core.training
figure.core.training.circle.fill
figure.cricket
figure.cricket.circle.fill
figure.cross.training
figure.cross.training.circle.fill
figure.curling
figure.curling.circle.fill
figure.dance
figure.dance.circle.fill
figure.disc.sports
figure.disc.sports.circle.fill
figure.dress.line.vertical.figure
figure.elliptical
figure.elliptical.circle.fill
figure.equestrian.sports
figure.equestrian.sports.circle.fill
figure.fall
figure.fall.circle.fill
figure.fencing
figure.fencing.circle.fill
figure.field.hockey
figure.field.hockey.circle
figure.field.hockey.circle.fill
figure.fishing
figure.fishing.circle.fill
figure.flexibility
figure.flexibility.circle.fill
figure.golf
figure.golf.circle.fill
figure.gymnastics
figure.gymnastics.circle.fill
figure.hand.cycling
figure.hand.cycling.circle.fill
figure.handball
figure.handball.circle.fill
figure.highintensity.intervaltraining
figure.highintensity.intervaltraining.circle.fill
figure.hiking
figure.hiking.circle.fill
figure.hockey
figure.hockey.circle.fill
figure.hunting
figure.hunting.circle.fill
figure.ice.hockey
figure.ice.hockey.circle
figure.ice.hockey.circle.fill
figure.ice.skating
figure.ice.skating.circle.fill
figure.indoor.cycle
figure.indoor.cycle.circle.fill
figure.indoor.rowing
figure.indoor.rowing.circle.fill
figure.indoor.soccer
figure.indoor.soccer.circle.fill
figure.jumprope
figure.jumprope.circle.fill
figure.kickboxing
figure.kickboxing.circle.fill
figure.lacrosse
figure.lacrosse.circle.fill
figure.martial.arts
figure.martial.arts.circle.fill
figure.mind.and.body
figure.mind.and.body.circle.fill
figure.mixed.cardio
figure.mixed.cardio.circle.fill
figure.open.water.swim
figure.open.water.swim.circle.fill
figure.outdoor.cycle
figure.outdoor.cycle.circle.fill
figure.outdoor.rowing
figure.outdoor.rowing.circle.fill
figure.outdoor.soccer
figure.outdoor.soccer.circle.fill
figure.pickleball
figure.pickleball.circle.fill
figure.pilates
figure.pilates.circle.fill
figure.play
figure.play.circle.fill
figure.pool.swim
figure.pool.swim.circle.fill
figure.racquetball
figure.racquetball.circle.fill
figure.roll
figure.roll.circle.fill
figure.roll.runningpace
figure.roll.runningpace.circle.fill
figure.rolling
figure.rolling.circle.fill
figure.rower
figure.rugby
figure.rugby.circle.fill
figure.run
figure.run.circle.fill
figure.run.square.stack
figure.run.square.stack.fill
figure.run.treadmill
figure.run.treadmill.circle.fill
figure.sailing
figure.sailing.circle.fill
figure.seated.side
figure.seated.side.air.distribution.lower
figure.seated.side.air.distribution.middle
figure.seated.side.air.distribution.middle.and.lower
figure.seated.side.air.distribution.middle.and.lower.angled
figure.seated.side.air.distribution.upper
figure.seated.side.air.distribution.upper.angled.and.lower.angled
figure.seated.side.air.distribution.upper.angled.and.middle
figure.seated.side.air.distribution.upper.angled.and.middle.and.lower.angled
figure.seated.side.air.lower
figure.seated.side.air.upper
figure.seated.side.air.upper.and.lower
figure.seated.side.air.windshield
figure.seated.side.airbag.off
figure.seated.side.airbag.off.2
figure.seated.side.airbag.on
figure.seated.side.airbag.on.2
figure.seated.side.automatic
figure.seated.side.right.child.lap
figure.seated.side.windshield.front.and.heat.waves
figure.seated.side.windshield.front.and.heat.waves.air.distribution.lower
figure.seated.side.windshield.front.and.heat.waves.air.distribution.middle
figure.seated.side.windshield.front.and.heat.waves.air.distribution.middle.and.lower
figure.seated.side.windshield.front.and.heat.waves.air.distribution.upper
figure.seated.side.windshield.front.and.heat.waves.air.distribution.upper.and.lower
figure.seated.side.windshield.front.and.heat.waves.air.distribution.upper.and.middle
figure.seated.side.windshield.front.and.heat.waves.air.distribution.upper.and.middle.and.lower
figure.skateboarding
figure.skateboarding.circle.fill
figure.skating
figure.skiing.crosscountry
figure.skiing.crosscountry.circle.fill
figure.skiing.downhill
figure.skiing.downhill.circle.fill
figure.snowboarding
figure.snowboarding.circle.fill
figure.soccer
figure.socialdance
figure.socialdance.circle.fill
figure.softball
figure.softball.circle.fill
figure.squash
figure.squash.circle.fill
figure.stair.stepper
figure.stair.stepper.circle.fill
figure.stairs
figure.stairs.circle.fill
figure.stand
figure.stand.dress
figure.stand.dress.line.vertical.figure
figure.stand.line.dotted.figure.stand
figure.step.training
figure.step.training.circle.fill
figure.strengthtraining.functional
figure.strengthtraining.functional.circle.fill
figure.strengthtraining.traditional
figure.strengthtraining.traditional.circle.fill
figure.surfing
figure.surfing.circle.fill
figure.table.tennis
figure.table.tennis.circle.fill
figure.taichi
figure.taichi.circle.fill
figure.tennis
figure.tennis.circle.fill
figure.track.and.field
figure.track.and.field.circle.fill
figure.volleyball
figure.volleyball.circle.fill
figure.walk
figure.walk.arrival
figure.walk.circle.fill
figure.walk.departure
figure.walk.diamond
figure.walk.diamond.fill
figure.walk.motion
figure.walk.motion.trianglebadge.exclamationmark
figure.walk.suitcase.rolling
figure.walk.suitcase.rolling.circle.fill
figure.walk.treadmill
figure.walk.treadmill.circle.fill
figure.walk.triangle
figure.walk.triangle.fill
figure.water.fitness
figure.water.fitness.circle.fill
figure.waterpolo
figure.waterpolo.circle.fill
figure.wave
figure.wave.circle.fill
figure.wrestling
figure.wrestling.circle.fill
figure.yoga
figure.yoga.circle.fill
filemenu.and.cursorarrow
filemenu.and.pointer.arrow
filemenu.and.selection
film
film.circle.fill
film.fill
film.stack
film.stack.fill
finder
fire.extinguisher
fire.extinguisher.fill
fireplace
fireplace.fill
firewall
firewall.fill
fireworks
fish
fish.circle.fill
fish.fill
flag
flag.2.crossed
flag.2.crossed.circle.fill
flag.2.crossed.fill
flag.and.flag.filled.crossed
flag.badge.ellipsis
flag.badge.ellipsis.fill
flag.checkered
flag.checkered.2.crossed
flag.checkered.circle
flag.checkered.circle.fill
flag.circle.fill
flag.fill
flag.filled.and.flag.crossed
flag.pattern.checkered
flag.pattern.checkered.2.crossed
flag.pattern.checkered.circle.fill
flag.slash
flag.slash.circle.fill
flag.slash.fill
flag.square
flag.square.fill
flame
flame.circle.fill
flame.fill
flashlight.off.circle.fill
flashlight.off.fill
flashlight.on.circle.fill
flashlight.on.fill
flashlight.slash
flashlight.slash.circle.fill
flask
flask.fill
flip.horizontal
flip.horizontal.fill
florinsign.arrow.circlepath
florinsign.bank.building
florinsign.bank.building.fill
flowchart
flowchart.fill
fn
folder
folder.badge.gear
folder.badge.gearshape
folder.badge.minus
folder.badge.person.crop
folder.badge.plus
folder.badge.questionmark
folder.circle.fill
folder.fill
folder.fill.badge.gear
folder.fill.badge.gearshape
folder.fill.badge.minus
folder.fill.badge.person.crop
folder.fill.badge.plus
folder.fill.badge.questionmark
football
football.circle
football.circle.fill
football.fill
fork.knife
fork.knife.circle.fill
formfitting.gamecontroller
formfitting.gamecontroller.fill
fossil.shell
fossil.shell.fill
francsign.arrow.circlepath
francsign.bank.building
francsign.bank.building.fill
frying.pan
frying.pan.fill
fx
gauge
gauge.badge.minus
gauge.badge.plus
gauge.high
gauge.low
gauge.medium
gauge.medium.badge.minus
gauge.medium.badge.plus
gauge.open.with.lines.needle.33percent.and.arrowtriangle.from.0percent.to.50percent
gauge.with.needle
gauge.with.needle.fill
gear
gear.badge
gear.badge.checkmark
gear.badge.questionmark
gear.badge.xmark
gear.circle.fill
gearshape
gearshape.2
gearshape.2.fill
gearshape.arrow.triangle.2.circlepath
gearshape.circle.fill
gearshape.fill
gearshift.layout.sixspeed
gift
gift.circle.fill
gift.fill
globe.americas
globe.americas.fill
globe.asia.australia
globe.asia.australia.fill
globe.badge.clock
globe.badge.clock.fill
globe.central.south.asia
globe.central.south.asia.fill
globe.desk
globe.desk.fill
globe.europe.africa
globe.europe.africa.fill
gobackward
gobackward.10
gobackward.15
gobackward.30
gobackward.45
gobackward.5
gobackward.60
gobackward.75
gobackward.90
gobackward.minus
goforward
goforward.10
goforward.15
goforward.30
goforward.45
goforward.5
goforward.60
goforward.75
goforward.90
goforward.plus
graduationcap
graduationcap.circle.fill
graduationcap.fill
greetingcard
greetingcard.fill
grid
grid.circle.fill
guaranisign.arrow.circlepath
guaranisign.bank.building
guaranisign.bank.building.fill
guidepoint.horizontal
guidepoint.vertical
guidepoint.vertical.arrowtriangle.forward
guidepoint.vertical.numbers
guitars
guitars.fill
gym.bag
gym.bag.fill
gyroscope
h.square.fill.on.square.fill
h.square.on.square
h.square.on.square.fill
hammer
hammer.circle.fill
hammer.fill
hand.app
hand.app.fill
hand.draw
hand.draw.badge.ellipsis
hand.draw.badge.ellipsis.fill
hand.draw.fill
hand.palm.facing
hand.palm.facing.fill
hand.pinch
hand.pinch.fill
hand.point.down
hand.point.down.fill
hand.point.left
hand.point.left.fill
hand.point.right
hand.point.right.fill
hand.point.up
hand.point.up.braille
hand.point.up.braille.badge.ellipsis
hand.point.up.braille.badge.ellipsis.fill
hand.point.up.braille.fill
hand.point.up.fill
hand.point.up.left
hand.point.up.left.and.text
hand.point.up.left.and.text.fill
hand.point.up.left.fill
hand.raised
hand.raised.app
hand.raised.app.fill
hand.raised.circle.fill
hand.raised.fill
hand.raised.fingers.spread
hand.raised.fingers.spread.fill
hand.raised.palm.facing
hand.raised.palm.facing.fill
hand.raised.slash
hand.raised.slash.fill
hand.raised.square
hand.raised.square.fill
hand.raised.square.on.square
hand.raised.square.on.square.fill
hand.rays
hand.rays.fill
hand.tap
hand.tap.fill
hand.thumbsdown
hand.thumbsdown.circle.fill
hand.thumbsdown.fill
hand.thumbsdown.filled.hand.thumbsup
hand.thumbsdown.hand.thumbsup
hand.thumbsdown.hand.thumbsup.fill
hand.thumbsdown.hand.thumbsup.filled
hand.thumbsdown.slash
hand.thumbsdown.slash.fill
hand.thumbsup
hand.thumbsup.circle.fill
hand.thumbsup.fill
hand.thumbsup.slash
hand.thumbsup.slash.fill
hand.wave
hand.wave.fill
handbag
handbag.circle.fill
handbag.fill
hands.and.sparkles
hands.and.sparkles.fill
hands.clap
hands.clap.fill
hands.sparkles
hands.sparkles.fill
hanger
hare
hare.circle.fill
hare.fill
hat.cap
hat.cap.fill
hat.widebrim
hat.widebrim.fill
head.profile.arrow.forward.and.vision.pro
head.profile.arrow.forward.and.visionpro
hearingaid.ear
heart.badge.bolt
heart.badge.bolt.fill
heart.badge.bolt.slash
heart.badge.bolt.slash.fill
heart.circle.fill
heart.fill
heart.rectangle
heart.rectangle.fill
heart.slash.circle.fill
heart.slash.fill
heart.square
heart.square.fill
heart.text.clipboard
heart.text.clipboard.fill
heart.text.square
heart.text.square.fill
heater.vertical
heater.vertical.fill
helm
helmet
helmet.fill
hexagon.bottomhalf.filled
hexagon.lefthalf.filled
hexagon.righthalf.filled
hexagon.tophalf.filled
hifireceiver
hifireceiver.fill
hifispeaker.and.homepodmini
hifispeaker.and.homepodmini.fill
highlighter
highlighter.badge.ellipsis
hockey.puck
hockey.puck.circle.fill
hockey.puck.fill
homekit
homepod.and.homepodmini
homepod.and.homepodmini.fill
homepodmini
homepodmini.2
homepodmini.2.fill
homepodmini.and.appletv
homepodmini.and.appletv.fill
homepodmini.fill
hourglass
hourglass.and.lock
hourglass.badge.eye
hourglass.badge.lock
hourglass.badge.plus
hourglass.bottomhalf.fill
hourglass.bottomhalf.filled
hourglass.circle.fill
hourglass.tophalf.fill
hourglass.tophalf.filled
house
house.and.flag
house.and.flag.circle.fill
house.and.flag.fill
house.circle.fill
house.fill
house.lodge
house.lodge.circle.fill
house.lodge.fill
house.slash
house.slash.fill
hryvniasign.arrow.circlepath
hryvniasign.bank.building
hryvniasign.bank.building.fill
humidifier
humidifier.fill
hurricane
hurricane.circle.fill
icloud
icloud.and.arrow.down
icloud.and.arrow.down.fill
icloud.and.arrow.up
icloud.and.arrow.up.fill
icloud.circle.fill
icloud.dashed
icloud.fill
icloud.slash
icloud.slash.fill
icloud.square
icloud.square.fill
indianrupeesign.arrow.circlepath
indianrupeesign.bank.building
indianrupeesign.bank.building.fill
info
info.bubble
info.bubble.fill
info.circle.fill
info.circle.text.page
info.circle.text.page.fill
info.triangle
info.triangle.fill
inhaler
inhaler.fill
inset.filled.bottomhalf.rectangle
inset.filled.bottomhalf.rectangle.portrait
inset.filled.bottomhalf.tophalf.rectangle
inset.filled.bottomleading.bottomtrailing.rectangle
inset.filled.bottomleading.rectangle
inset.filled.bottomleading.rectangle.portrait
inset.filled.bottomleft.bottomright.rectangle
inset.filled.bottomleft.rectangle
inset.filled.bottomleft.rectangle.portrait
inset.filled.bottomright.rectangle
inset.filled.bottomright.rectangle.portrait
inset.filled.bottomthird.rectangle
inset.filled.bottomthird.rectangle.portrait
inset.filled.bottomthird.square
inset.filled.bottomtrailing.rectangle
inset.filled.bottomtrailing.rectangle.portrait
inset.filled.capsule
inset.filled.capsule.portrait
inset.filled.center.rectangle
inset.filled.center.rectangle.badge.plus
inset.filled.center.rectangle.portrait
inset.filled.circle.dashed
inset.filled.diamond
inset.filled.leadinghalf.arrow.leading.rectangle
inset.filled.leadinghalf.rectangle
inset.filled.leadinghalf.rectangle.portrait
inset.filled.leadinghalf.toptrailing.bottomtrailing.rectangle
inset.filled.leadinghalf.trailinghalf.rectangle
inset.filled.leadingthird.rectangle
inset.filled.leadingthird.rectangle.portrait
inset.filled.leadingthird.square
inset.filled.lefthalf.arrow.left.rectangle
inset.filled.lefthalf.rectangle
inset.filled.lefthalf.rectangle.portrait
inset.filled.lefthalf.righthalf.rectangle
inset.filled.lefthalf.topright.bottomright.rectangle
inset.filled.leftthird.rectangle
inset.filled.leftthird.rectangle.portrait
inset.filled.leftthird.square
inset.filled.oval
inset.filled.oval.portrait
inset.filled.pano
inset.filled.rectangle
inset.filled.rectangle.and.cursorarrow
inset.filled.rectangle.and.person.filled
inset.filled.rectangle.and.person.filled.circle.fill
inset.filled.rectangle.and.person.filled.slash
inset.filled.rectangle.and.pointer.arrow
inset.filled.rectangle.badge.record
inset.filled.rectangle.on.rectangle
inset.filled.rectangle.portrait
inset.filled.righthalf.arrow.right.rectangle
inset.filled.righthalf.lefthalf.rectangle
inset.filled.righthalf.rectangle
inset.filled.righthalf.rectangle.portrait
inset.filled.rightthird.rectangle
inset.filled.rightthird.rectangle.portrait
inset.filled.rightthird.square
inset.filled.square
inset.filled.square.dashed
inset.filled.tophalf.bottomhalf.rectangle
inset.filled.tophalf.bottomleft.bottomright.rectangle
inset.filled.tophalf.rectangle
inset.filled.tophalf.rectangle.portrait
inset.filled.topleading.bottomleading.trailinghalf.rectangle
inset.filled.topleading.rectangle
inset.filled.topleading.rectangle.portrait
inset.filled.topleft.bottomleft.righthalf.rectangle
inset.filled.topleft.rectangle
inset.filled.topleft.rectangle.portrait
inset.filled.topleft.topright.bottomhalf.rectangle
inset.filled.topleft.topright.bottomleft.bottomright.rectangle
inset.filled.topright.rectangle
inset.filled.topright.rectangle.portrait
inset.filled.topthird.rectangle
inset.filled.topthird.rectangle.portrait
inset.filled.topthird.square
inset.filled.toptrailing.rectangle
inset.filled.toptrailing.rectangle.portrait
inset.filled.trailinghalf.arrow.trailing.rectangle
inset.filled.trailinghalf.leadinghalf.rectangle
inset.filled.trailinghalf.rectangle
inset.filled.trailinghalf.rectangle.portrait
inset.filled.trailingthird.rectangle
inset.filled.trailingthird.rectangle.portrait
inset.filled.trailingthird.square
inset.filled.triangle
internaldrive
internaldrive.fill
ipad.and.iphone
ipad.and.iphone.slash
ipad.homebutton
ipad.homebutton.badge.play
ipad.homebutton.landscape
ipad.homebutton.landscape.badge.play
iphone.and.arrow.forward
iphone.and.arrow.left.and.arrow.right
iphone.homebutton
iphone.homebutton.badge.play
iphone.homebutton.circle
iphone.homebutton.circle.fill
iphone.homebutton.landscape
iphone.homebutton.radiowaves.left.and.right
iphone.homebutton.radiowaves.left.and.right.circle
iphone.homebutton.radiowaves.left.and.right.circle.fill
iphone.homebutton.slash
iphone.homebutton.slash.circle
iphone.homebutton.slash.circle.fill
ipodshuffle.gen1
ipodshuffle.gen2
ipodshuffle.gen3
ipodshuffle.gen4
ipodtouch
ipodtouch.landscape
ipodtouch.slash
ivfluid.bag
ivfluid.bag.fill
j.square.fill.on.square.fill
j.square.on.square
j.square.on.square.fill
jacket
jacket.circle.fill
jacket.fill
k
key.2.on.ring
key.2.on.ring.fill
key.icloud
key.icloud.fill
key.shield
key.shield.fill
key.viewfinder
keyboard.macwindow
kipsign.arrow.circlepath
kipsign.bank.building
kipsign.bank.building.fill
l.button.roundedbottom.horizontal
l.button.roundedbottom.horizontal.fill
l.joystick
l.joystick.down
l.joystick.down.fill
l.joystick.fill
l.joystick.press.down
l.joystick.press.down.fill
l.joystick.tilt.down
l.joystick.tilt.down.fill
l.joystick.tilt.left
l.joystick.tilt.left.fill
l.joystick.tilt.right
l.joystick.tilt.right.fill
l.joystick.tilt.up
l.joystick.tilt.up.fill
l.rectangle.roundedbottom
l.rectangle.roundedbottom.fill
l1.button.roundedbottom.horizontal
l1.button.roundedbottom.horizontal.fill
l1.circle.fill
l1.rectangle.roundedbottom
l1.rectangle.roundedbottom.fill
l2.button.angledtop.vertical.left
l2.button.angledtop.vertical.left.fill
l2.button.roundedtop.horizontal
l2.button.roundedtop.horizontal.fill
l2.circle.fill
l2.rectangle.roundedtop
l2.rectangle.roundedtop.fill
l3.button.angledbottom.horizontal.left
l3.button.angledbottom.horizontal.left.fill
l4.button.horizontal
l4.button.horizontal.fill
ladybug
ladybug.circle.fill
ladybug.fill
ladybug.slash
ladybug.slash.circle.fill
ladybug.slash.fill
lamp.ceiling
lamp.ceiling.fill
lamp.ceiling.inverse
lamp.desk
lamp.desk.fill
lamp.floor
lamp.floor.fill
lamp.table
lamp.table.fill
lane
lanyardcard
lanyardcard.fill
laptopcomputer.and.ipad
laptopcomputer.and.iphone
largecircle.fill.circle
larisign.arrow.circlepath
larisign.bank.building
larisign.bank.building.fill
laser.burst
lasso
lasso.and.sparkles
lasso.badge.sparkles
lasso.sparkles
latch.2.case
latch.2.case.fill
laurel.leading
laurel.leading.laurel.trailing
laurel.trailing
lb.button.roundedbottom.horizontal
lb.button.roundedbottom.horizontal.fill
lb.circle.fill
lb.rectangle.roundedbottom
lb.rectangle.roundedbottom.fill
leaf
leaf.arrow.circlepath
leaf.arrow.triangle.circlepath
leaf.circle.fill
leaf.fill
left
left.circle.fill
level
level.fill
lifepreserver
lifepreserver.fill
light.beacon.max
light.beacon.max.fill
light.beacon.min
light.beacon.min.fill
light.cylindrical.ceiling
light.cylindrical.ceiling.fill
light.cylindrical.ceiling.inverse
light.panel
light.panel.fill
light.recessed
light.recessed.3
light.recessed.3.fill
light.recessed.3.inverse
light.recessed.fill
light.recessed.inverse
light.ribbon
light.ribbon.fill
light.strip.2
light.strip.2.fill
lightbulb
lightbulb.2
lightbulb.2.fill
lightbulb.circle.fill
lightbulb.fill
lightbulb.led
lightbulb.led.fill
lightbulb.led.wide
lightbulb.led.wide.fill
lightbulb.max
lightbulb.max.fill
lightbulb.min
lightbulb.min.badge.exclamationmark
lightbulb.min.badge.exclamationmark.fill
lightbulb.min.fill
lightbulb.slash
lightbulb.slash.fill
lightrail
lightrail.fill
lightspectrum.horizontal
lightswitch.off
lightswitch.off.fill
lightswitch.off.square
lightswitch.off.square.fill
lightswitch.on
lightswitch.on.fill
lightswitch.on.square
lightswitch.on.square.fill
line.2.horizontal.decrease.circle.fill
line.3.crossed.swirl.circle
line.3.crossed.swirl.circle.fill
line.3.horizontal
line.3.horizontal.button.angledtop.vertical.right
line.3.horizontal.button.angledtop.vertical.right.fill
line.3.horizontal.circle.fill
line.3.horizontal.decrease
line.3.horizontal.decrease.circle.fill
line.diagonal
line.diagonal.arrow
line.diagonal.trianglehead.up.right
line.diagonal.trianglehead.up.right.left.down
line.horizontal.2.decrease.circle
line.horizontal.2.decrease.circle.fill
line.horizontal.3
line.horizontal.3.circle
line.horizontal.3.circle.fill
line.horizontal.3.decrease
line.horizontal.3.decrease.circle
line.horizontal.3.decrease.circle.fill
line.horizontal.star.fill.line.horizontal
lineweight
link
link.badge.plus
link.circle.fill
link.icloud
link.icloud.fill
lirasign.arrow.circlepath
lirasign.bank.building
lirasign.bank.building.fill
list.and.film
list.bullet.below.rectangle
list.bullet.clipboard
list.bullet.clipboard.fill
list.bullet.rectangle
list.bullet.rectangle.fill
list.bullet.rectangle.portrait
list.bullet.rectangle.portrait.fill
list.clipboard
list.clipboard.fill
list.dash.header.rectangle
list.dash.header.rectangle.fill
livephoto.badge.a
livephoto.badge.automatic
livephoto.play
livephoto.slash
lizard
lizard.circle.fill
lizard.fill
lm.button.horizontal
lm.button.horizontal.fill
location.fill.viewfinder
location.magnifyingglass
location.viewfinder
lock
lock.app.dashed
lock.badge.checkmark
lock.badge.checkmark.fill
lock.badge.clock
lock.badge.clock.fill
lock.badge.xmark
lock.badge.xmark.fill
lock.circle.dotted
lock.circle.fill
lock.doc
lock.doc.fill
lock.document
lock.document.fill
lock.fill
lock.heart.fill
lock.icloud
lock.icloud.fill
lock.open
lock.open.fill
lock.open.rotation
lock.open.trianglebadge.exclamationmark
lock.open.trianglebadge.exclamationmark.fill
lock.rectangle
lock.rectangle.dashed
lock.rectangle.fill
lock.rectangle.on.rectangle
lock.rectangle.on.rectangle.dashed
lock.rectangle.on.rectangle.fill
lock.rectangle.stack
lock.rectangle.stack.fill
lock.rotation
lock.rotation.open
lock.shield
lock.shield.fill
lock.slash
lock.slash.fill
lock.square
lock.square.dashed
lock.square.fill
lock.square.stack
lock.square.stack.fill
lock.trianglebadge.exclamationmark
lock.trianglebadge.exclamationmark.fill
logo.playstation
logo.xbox
long.text.page.and.pencil
long.text.page.and.pencil.fill
loupe
lsb.button.angledbottom.horizontal.left
lsb.button.angledbottom.horizontal.left.fill
lt.button.roundedtop.horizontal
lt.button.roundedtop.horizontal.fill
lt.circle.fill
lt.rectangle.roundedtop
lt.rectangle.roundedtop.fill
lungs
lungs.fill
m1.button.horizontal
m1.button.horizontal.fill
m2.button.horizontal
m2.button.horizontal.fill
m3.button.horizontal
m3.button.horizontal.fill
m4.button.horizontal
m4.button.horizontal.fill
macbook.and.visionpro
macpro.gen3.badge.ckeckmark
macpro.gen3.badge.ckeckmark.fill
macwindow
macwindow.and.cursorarrow
macwindow.and.pointer.arrow
macwindow.badge.plus
macwindow.on.rectangle
macwindow.stack
magazine
magazine.fill
magnifyingglass
magnifyingglass.circle.fill
mail
mail.and.text.magnifyingglass
mail.fill
mail.stack
mail.stack.fill
malaysianringgitsign.bank.building
malaysianringgitsign.bank.building.fill
manatsign.arrow.circlepath
manatsign.bank.building
manatsign.bank.building.fill
map
map.circle.fill
map.fill
mappin
mappin.and.ellipse
mappin.and.ellipse.circle.fill
mappin.circle.fill
mappin.slash
mappin.slash.circle.fill
mappin.square
mappin.square.fill
matter.logo
medal
medal.fill
medal.star
medal.star.fill
medical.thermometer
medical.thermometer.fill
megaphone
megaphone.fill
memorychip
memorychip.fill
menubar.arrow.down.rectangle
menubar.arrow.up.rectangle
menubar.dock.rectangle
menubar.dock.rectangle.badge.record
menubar.rectangle
menucard
menucard.fill
message
message.and.waveform
message.and.waveform.fill
message.badge
message.badge.circle.fill
message.badge.fill
message.badge.filled.fill
message.circle.fill
message.fill
metronome
metronome.fill
mic
mic.and.signal.meter
mic.and.signal.meter.fill
mic.badge.plus
mic.badge.xmark
mic.circle
mic.circle.fill
mic.fill
mic.fill.badge.plus
mic.fill.badge.xmark
mic.slash
mic.slash.circle
mic.slash.circle.fill
mic.slash.fill
mic.square
mic.square.fill
microbe
microbe.circle.fill
microbe.fill
microphone
microphone.badge.ellipsis
microphone.badge.ellipsis.fill
microphone.badge.plus
microphone.badge.plus.fill
microphone.badge.xmark
microphone.badge.xmark.fill
microphone.circle.fill
microphone.fill
microphone.slash
microphone.slash.circle.fill
microphone.slash.fill
microphone.square
microphone.square.fill
microwave
microwave.fill
millsign.arrow.circlepath
millsign.bank.building
millsign.bank.building.fill
minus.arrow.trianglehead.clockwise
minus.diamond
minus.diamond.fill
minus.magnifyingglass
minus.rectangle.portrait
minus.rectangle.portrait.fill
minus.slash.plus
moon
moon.circle.fill
moon.dust
moon.dust.circle.fill
moon.dust.fill
moon.fill
moon.haze
moon.haze.circle.fill
moon.haze.fill
moon.stars
moon.stars.circle.fill
moon.stars.fill
moon.zzz
moon.zzz.fill
moonphase.first.quarter
moonphase.first.quarter.inverse
moonphase.full.moon
moonphase.full.moon.inverse
moonphase.last.quarter
moonphase.last.quarter.inverse
moonphase.new.moon
moonphase.new.moon.inverse
moonphase.waning.crescent
moonphase.waning.crescent.inverse
moonphase.waning.gibbous
moonphase.waning.gibbous.inverse
moonphase.waxing.crescent
moonphase.waxing.crescent.inverse
moonphase.waxing.gibbous
moonphase.waxing.gibbous.inverse
moonrise
moonrise.circle.fill
moonrise.fill
moonset
moonset.circle.fill
moonset.fill
moped
moped.fill
mosaic
mosaic.fill
motorcycle
motorcycle.fill
mountain.2
mountain.2.circle.fill
mountain.2.fill
mouth
mouth.fill
move.3d
movieclapper
movieclapper.fill
mug
mug.fill
music.house
music.house.fill
music.mic
music.mic.circle
music.mic.circle.fill
music.microphone
music.microphone.circle
music.microphone.circle.fill
music.note
music.note.list
music.note.slash
music.note.square.stack
music.note.square.stack.fill
music.pages
music.pages.fill
music.quarternote.3
mustache
mustache.fill
nairasign.arrow.circlepath
nairasign.bank.building
nairasign.bank.building.fill
network
network.badge.shield.half.filled
network.slash
newspaper
newspaper.circle.fill
newspaper.fill
norwegiankronesign.arrow.circlepath
norwegiankronesign.bank.building
norwegiankronesign.bank.building.fill
nose
nose.fill
nosign
nosign.app
nosign.app.fill
nosign.badge.clock
note
note.text
note.text.badge.plus
number
number.circle
number.circle.fill
number.square
number.square.fill
numbersign
oar.2.crossed
oar.2.crossed.circle.fill
octagon.bottomhalf.filled
octagon.lefthalf.filled
octagon.righthalf.filled
octagon.tophalf.filled
opticaldisc
opticaldisc.fill
opticaldiscdrive
opticaldiscdrive.fill
oval.bottomhalf.filled
oval.inset.filled
oval.lefthalf.filled
oval.portrait.bottomhalf.filled
oval.portrait.inset.filled
oval.portrait.lefthalf.filled
oval.portrait.righthalf.filled
oval.portrait.tophalf.filled
oval.righthalf.filled
oval.tophalf.filled
oven
oven.fill
p1.button.horizontal
p1.button.horizontal.fill
p2.button.horizontal
p2.button.horizontal.fill
p3.button.horizontal
p3.button.horizontal.fill
p4.button.horizontal
p4.button.horizontal.fill
pad.header
paddleshifter.left
paddleshifter.left.fill
paddleshifter.right
paddleshifter.right.fill
paint.bucket.classic
paintbrush
paintbrush.fill
paintbrush.pointed
paintbrush.pointed.fill
paintpalette
paintpalette.fill
pano
pano.badge.play
pano.badge.play.fill
pano.fill
paperclip
paperclip.badge.ellipsis
paperclip.circle.fill
paperplane
paperplane.circle.fill
paperplane.fill
paragraph
parentheses
party.popper
party.popper.fill
pawprint
pawprint.circle.fill
pawprint.fill
peacesign
pedal.accelerator
pedal.accelerator.fill
pedal.brake
pedal.brake.fill
pedal.clutch
pedal.clutch.fill
pedestrian.gate.closed
pedestrian.gate.closed.trianglebadge.exclamationmark
pedestrian.gate.open
pedestrian.gate.open.trianglebadge.exclamationmark
pencil
pencil.and.ellipsis.rectangle
pencil.and.list.clipboard
pencil.and.outline
pencil.and.ruler
pencil.and.ruler.fill
pencil.and.scribble
pencil.circle.fill
pencil.line
pencil.slash
pencil.tip
pencil.tip.crop.circle
pencil.tip.crop.circle.badge.arrow.forward
pencil.tip.crop.circle.badge.arrow.forward.fill
pencil.tip.crop.circle.badge.minus
pencil.tip.crop.circle.badge.minus.fill
pencil.tip.crop.circle.badge.plus
pencil.tip.crop.circle.badge.plus.fill
pencil.tip.crop.circle.fill
pentagon.bottomhalf.filled
pentagon.lefthalf.filled
pentagon.righthalf.filled
pentagon.tophalf.filled
person
person.2
person.2.badge
person.2.badge.fill
person.2.badge.gearshape
person.2.badge.gearshape.fill
person.2.badge.key
person.2.badge.key.fill
person.2.badge.minus
person.2.badge.minus.fill
person.2.badge.plus
person.2.badge.plus.fill
person.2.circle.fill
person.2.crop.square.stack
person.2.crop.square.stack.fill
person.2.fill
person.2.gobackward
person.2.shield
person.2.shield.fill
person.2.slash
person.2.slash.fill
person.2.square.stack
person.2.square.stack.fill
person.3
person.3.fill
person.and.arrow.left.and.arrow.right
person.and.arrow.left.and.arrow.right.outward
person.and.background.dotted
person.and.background.striped.horizontal
person.badge.clock
person.badge.clock.fill
person.badge.key
person.badge.key.fill
person.badge.minus
person.badge.minus.fill
person.badge.plus
person.badge.plus.fill
person.badge.shield.checkmark
person.badge.shield.checkmark.fill
person.badge.shield.exclamationmark
person.badge.shield.exclamationmark.fill
person.bubble
person.bubble.fill
person.bust
person.bust.circle.fill
person.bust.fill
person.checkmark.and.xmark
person.circle.fill
person.crop.artframe
person.crop.badge.magnifyingglass
person.crop.badge.magnifyingglass.fill
person.crop.circle
person.crop.circle.badge
person.crop.circle.badge.checkmark
person.crop.circle.badge.clock
person.crop.circle.badge.clock.fill
person.crop.circle.badge.ellipsis
person.crop.circle.badge.ellipsis.fill
person.crop.circle.badge.exclam
person.crop.circle.badge.exclamationmark
person.crop.circle.badge.exclamationmark.fill
person.crop.circle.badge.fill
person.crop.circle.badge.minus
person.crop.circle.badge.moon
person.crop.circle.badge.moon.fill
person.crop.circle.badge.plus
person.crop.circle.badge.questionmark
person.crop.circle.badge.questionmark.fill
person.crop.circle.badge.xmark
person.crop.circle.dashed
person.crop.circle.dashed.circle.fill
person.crop.circle.fill
person.crop.circle.fill.badge.checkmark
person.crop.circle.fill.badge.exclam
person.crop.circle.fill.badge.exclamationmark
person.crop.circle.fill.badge.minus
person.crop.circle.fill.badge.plus
person.crop.circle.fill.badge.questionmark
person.crop.circle.fill.badge.xmark
person.crop.rectangle
person.crop.rectangle.badge.plus
person.crop.rectangle.badge.plus.fill
person.crop.rectangle.fill
person.crop.rectangle.stack
person.crop.rectangle.stack.fill
person.crop.square
person.crop.square.badge.camera
person.crop.square.badge.camera.fill
person.crop.square.badge.video
person.crop.square.badge.video.fill
person.crop.square.fill
person.crop.square.fill.and.at.rectangle
person.crop.square.filled.and.at.rectangle
person.crop.square.filled.and.at.rectangle.fill
person.crop.square.on.square.angled
person.crop.square.on.square.angled.fill
person.fill
person.fill.and.arrow.left.and.arrow.right
person.fill.and.arrow.left.and.arrow.right.outward
person.fill.badge.minus
person.fill.badge.plus
person.fill.checkmark
person.fill.checkmark.and.xmark
person.fill.questionmark
person.fill.turn.down
person.fill.turn.left
person.fill.turn.right
person.fill.viewfinder
person.fill.xmark
person.icloud
person.icloud.fill
person.line.dotted.person
person.line.dotted.person.fill
person.slash
person.slash.fill
person.text.rectangle
person.text.rectangle.fill
person.text.rectangle.trianglebadge.exclamationmark
person.text.rectangle.trianglebadge.exclamationmark.fill
personalhotspot
personalhotspot.circle.fill
personalhotspot.slash
perspective
peruviansolessign.bank.building
peruviansolessign.bank.building.fill
pesetasign.arrow.circlepath
pesetasign.bank.building
pesetasign.bank.building.fill
pesosign.arrow.circlepath
pesosign.bank.building
pesosign.bank.building.fill
pet.carrier
pet.carrier.circle.fill
pet.carrier.fill
phone
phone.and.waveform
phone.and.waveform.fill
phone.arrow.down.left
phone.arrow.down.left.fill
phone.arrow.right
phone.arrow.right.fill
phone.arrow.up.right
phone.arrow.up.right.circle.fill
phone.arrow.up.right.fill
phone.badge.checkmark
phone.badge.clock
phone.badge.clock.fill
phone.badge.plus
phone.bubble
phone.bubble.fill
phone.bubble.left
phone.bubble.left.fill
phone.circle.fill
phone.connection
phone.connection.fill
phone.down
phone.down.circle.fill
phone.down.fill
phone.fill
phone.fill.arrow.down.left
phone.fill.arrow.right
phone.fill.arrow.up.right
phone.fill.badge.checkmark
phone.fill.badge.plus
phone.fill.connection
photo
photo.artframe
photo.artframe.circle.fill
photo.badge.arrow.down
photo.badge.arrow.down.fill
photo.badge.checkmark
photo.badge.checkmark.fill
photo.badge.exclamationmark
photo.badge.exclamationmark.fill
photo.badge.magnifyingglass
photo.badge.magnifyingglass.fill
photo.badge.plus
photo.badge.plus.fill
photo.badge.shield.exclamationmark
photo.badge.shield.exclamationmark.fill
photo.circle.fill
photo.fill
photo.fill.on.rectangle.fill
photo.on.rectangle
photo.on.rectangle.angled
photo.on.rectangle.angled.fill
photo.stack
photo.stack.fill
photo.trianglebadge.exclamationmark
photo.trianglebadge.exclamationmark.fill
pianokeys
pianokeys.inverse
pill
pill.circle.fill
pill.fill
pills
pills.circle.fill
pills.fill
pin
pin.circle.fill
pin.fill
pin.slash
pin.slash.fill
pin.square
pin.square.fill
pip
pip.enter
pip.exit
pip.fill
pip.remove
pip.swap
pipe.and.drop
pipe.and.drop.fill
placeholdertext.fill
play.rectangle.on.rectangle
play.rectangle.on.rectangle.circle.fill
play.rectangle.on.rectangle.fill
playstation.logo
plus.app
plus.app.fill
plus.bubble
plus.bubble.fill
plus.capsule
plus.capsule.fill
plus.circle.dashed
plus.diamond
plus.diamond.fill
plus.magnifyingglass
plus.message
plus.message.fill
plus.minus.capsule
plus.minus.capsule.fill
plus.rectangle.fill.on.folder.fill
plus.rectangle.fill.on.rectangle.fill
plus.rectangle.on.folder
plus.rectangle.on.folder.fill
plus.rectangle.on.rectangle
plus.rectangle.portrait
plus.rectangle.portrait.fill
plus.slash.minus
plus.square.dashed
plus.square.fill.on.square.fill
plus.square.on.square
plus.viewfinder
point.3.connected.trianglepath.dotted
point.3.filled.connected.trianglepath.dotted
point.bottomleft.filled.forward.to.point.topright.scurvepath
point.bottomleft.forward.to.arrow.triangle.scurvepath
point.bottomleft.forward.to.arrow.triangle.scurvepath.fill
point.bottomleft.forward.to.arrow.triangle.uturn.scurvepath
point.bottomleft.forward.to.arrow.triangle.uturn.scurvepath.fill
point.bottomleft.forward.to.arrowtriangle.uturn.scurvepath
point.bottomleft.forward.to.arrowtriangle.uturn.scurvepath.fill
point.bottomleft.forward.to.point.topright.filled.scurvepath
point.bottomleft.forward.to.point.topright.scurvepath
point.bottomleft.forward.to.point.topright.scurvepath.fill
point.fill.topleft.down.curvedto.point.fill.bottomright.up
point.filled.topleft.down.curvedto.point.bottomright.up
point.forward.to.point.capsulepath
point.forward.to.point.capsulepath.fill
point.topleft.down.curvedto.point.bottomright.up
point.topleft.down.curvedto.point.bottomright.up.fill
point.topleft.down.curvedto.point.filled.bottomright.up
point.topleft.down.to.point.bottomright.curvepath
point.topleft.down.to.point.bottomright.curvepath.fill
point.topleft.down.to.point.bottomright.filled.curvepath
point.topleft.filled.down.to.point.bottomright.curvepath
point.topright.arrow.triangle.backward.to.point.bottomleft.filled.scurvepath
point.topright.arrow.triangle.backward.to.point.bottomleft.scurvepath
point.topright.arrow.triangle.backward.to.point.bottomleft.scurvepath.fill
point.topright.filled.arrow.triangle.backward.to.point.bottomleft.scurvepath
pointer.arrow
pointer.arrow.and.square.on.square.dashed
pointer.arrow.click
pointer.arrow.click.badge.clock
pointer.arrow.ipad
pointer.arrow.ipad.and.square.on.square.dashed
pointer.arrow.ipad.rays
pointer.arrow.ipad.slash
pointer.arrow.ipad.slash.square
pointer.arrow.ipad.slash.square.fill
pointer.arrow.ipad.square
pointer.arrow.ipad.square.fill
pointer.arrow.motionlines
pointer.arrow.motionlines.click
pointer.arrow.rays
pointer.arrow.slash
pointer.arrow.slash.square
pointer.arrow.slash.square.fill
pointer.arrow.square
pointer.arrow.square.fill
polishzlotysign.arrow.circlepath
polishzlotysign.bank.building
polishzlotysign.bank.building.fill
popcorn
popcorn.circle.fill
popcorn.fill
poweroff
poweron
poweroutlet.strip
poweroutlet.strip.fill
poweroutlet.type.a
poweroutlet.type.a.fill
poweroutlet.type.a.square
poweroutlet.type.a.square.fill
poweroutlet.type.b
poweroutlet.type.b.fill
poweroutlet.type.b.square
poweroutlet.type.b.square.fill
poweroutlet.type.c
poweroutlet.type.c.fill
poweroutlet.type.c.square
poweroutlet.type.c.square.fill
poweroutlet.type.d
poweroutlet.type.d.fill
poweroutlet.type.d.square
poweroutlet.type.d.square.fill
poweroutlet.type.e
poweroutlet.type.e.fill
poweroutlet.type.e.square
poweroutlet.type.e.square.fill
poweroutlet.type.f
poweroutlet.type.f.fill
poweroutlet.type.f.square
poweroutlet.type.f.square.fill
poweroutlet.type.g
poweroutlet.type.g.fill
poweroutlet.type.g.square
poweroutlet.type.g.square.fill
poweroutlet.type.h
poweroutlet.type.h.fill
poweroutlet.type.h.square
poweroutlet.type.h.square.fill
poweroutlet.type.i
poweroutlet.type.i.fill
poweroutlet.type.i.square
poweroutlet.type.i.square.fill
poweroutlet.type.j
poweroutlet.type.j.fill
poweroutlet.type.j.square
poweroutlet.type.j.square.fill
poweroutlet.type.k
poweroutlet.type.k.fill
poweroutlet.type.k.square
poweroutlet.type.k.square.fill
poweroutlet.type.l
poweroutlet.type.l.fill
poweroutlet.type.l.square
poweroutlet.type.l.square.fill
poweroutlet.type.m
poweroutlet.type.m.fill
poweroutlet.type.m.square
poweroutlet.type.m.square.fill
poweroutlet.type.n
poweroutlet.type.n.fill
poweroutlet.type.n.square
poweroutlet.type.n.square.fill
poweroutlet.type.o
poweroutlet.type.o.fill
poweroutlet.type.o.square
poweroutlet.type.o.square.fill
powerplug
powerplug.fill
powerplug.portrait
powerplug.portrait.fill
powersleep
printer.dotmatrix.fill.and.paper.fill
printer.fill.and.paper.fill
purchased
purchased.circle.fill
puzzlepiece
puzzlepiece.extension
puzzlepiece.extension.fill
puzzlepiece.fill
pyramid
pyramid.fill
qrcode
qrcode.viewfinder
questionmark
questionmark.app
questionmark.app.dashed
questionmark.app.fill
questionmark.bubble
questionmark.bubble.fill
questionmark.circle.dashed
questionmark.diamond
questionmark.diamond.fill
questionmark.folder
questionmark.folder.fill
questionmark.message
questionmark.message.fill
questionmark.square.dashed
questionmark.text.page
questionmark.text.page.fill
questionmark.video
questionmark.video.fill
quote.bubble
quote.bubble.fill
quote.closing
quote.opening
r.button.roundedbottom.horizontal
r.button.roundedbottom.horizontal.fill
r.joystick
r.joystick.down
r.joystick.down.fill
r.joystick.fill
r.joystick.press.down
r.joystick.press.down.fill
r.joystick.tilt.down
r.joystick.tilt.down.fill
r.joystick.tilt.left
r.joystick.tilt.left.fill
r.joystick.tilt.right
r.joystick.tilt.right.fill
r.joystick.tilt.up
r.joystick.tilt.up.fill
r.rectangle.roundedbottom
r.rectangle.roundedbottom.fill
r.square.fill.on.square.fill
r.square.on.square
r.square.on.square.fill
r1.button.roundedbottom.horizontal
r1.button.roundedbottom.horizontal.fill
r1.circle.fill
r1.rectangle.roundedbottom
r1.rectangle.roundedbottom.fill
r2.button.angledtop.vertical.right
r2.button.angledtop.vertical.right.fill
r2.button.roundedtop.horizontal
r2.button.roundedtop.horizontal.fill
r2.circle.fill
r2.rectangle.roundedtop
r2.rectangle.roundedtop.fill
r3.button.angledbottom.horizontal.right
r3.button.angledbottom.horizontal.right.fill
r4.button.horizontal
r4.button.horizontal.fill
radio
radio.fill
radiowaves.left
radiowaves.right
rb.button.roundedbottom.horizontal
rb.button.roundedbottom.horizontal.fill
rb.circle.fill
rb.rectangle.roundedbottom
rb.rectangle.roundedbottom.fill
receipt
receipt.fill
recordingtape
recordingtape.circle.fill
rectangle.2.swap
rectangle.3.group
rectangle.3.group.bubble
rectangle.3.group.bubble.fill
rectangle.3.group.bubble.left
rectangle.3.group.bubble.left.fill
rectangle.3.group.dashed
rectangle.3.group.fill
rectangle.3.offgrid
rectangle.3.offgrid.bubble.left
rectangle.3.offgrid.bubble.left.fill
rectangle.3.offgrid.fill
rectangle.and.arrow.up.right.and.arrow.down.left
rectangle.and.arrow.up.right.and.arrow.down.left.slash
rectangle.and.hand.point.up.left
rectangle.and.hand.point.up.left.fill
rectangle.and.hand.point.up.left.filled
rectangle.and.paperclip
rectangle.and.text.magnifyingglass
rectangle.arrowtriangle.2.inward
rectangle.arrowtriangle.2.outward
rectangle.badge.checkmark
rectangle.badge.minus
rectangle.badge.person.crop
rectangle.badge.plus
rectangle.badge.sparkles
rectangle.badge.sparkles.fill
rectangle.badge.xmark
rectangle.bottomhalf.filled
rectangle.bottomhalf.inset.filled
rectangle.bottomthird.inset.fill
rectangle.bottomthird.inset.filled
rectangle.center.inset.fill
rectangle.center.inset.filled
rectangle.center.inset.filled.badge.plus
rectangle.checkered
rectangle.compress.vertical
rectangle.connected.to.line.below
rectangle.dashed
rectangle.dashed.and.paperclip
rectangle.dashed.badge.record
rectangle.dock
rectangle.expand.diagonal
rectangle.expand.vertical
rectangle.fill.badge.checkmark
rectangle.fill.badge.minus
rectangle.fill.badge.person.crop
rectangle.fill.badge.plus
rectangle.fill.badge.xmark
rectangle.fill.on.rectangle.angled.fill
rectangle.fill.on.rectangle.fill
rectangle.fill.on.rectangle.fill.circle
rectangle.fill.on.rectangle.fill.circle.fill
rectangle.fill.on.rectangle.fill.slash.fill
rectangle.filled.and.hand.point.up.left
rectangle.grid.1x2
rectangle.grid.1x2.fill
rectangle.grid.1x3
rectangle.grid.1x3.fill
rectangle.grid.2x2
rectangle.grid.2x2.fill
rectangle.grid.3x1
rectangle.grid.3x1.fill
rectangle.grid.3x2
rectangle.grid.3x2.fill
rectangle.grid.3x3
rectangle.grid.3x3.fill
rectangle.inset.bottomleading.filled
rectangle.inset.bottomleft.fill
rectangle.inset.bottomleft.filled
rectangle.inset.bottomright.fill
rectangle.inset.bottomright.filled
rectangle.inset.bottomtrailing.filled
rectangle.inset.fill
rectangle.inset.filled
rectangle.inset.filled.and.cursorarrow
rectangle.inset.filled.and.person.filled
rectangle.inset.filled.badge.record
rectangle.inset.filled.on.rectangle
rectangle.inset.topleading.filled
rectangle.inset.topleft.fill
rectangle.inset.topleft.filled
rectangle.inset.topright.fill
rectangle.inset.topright.filled
rectangle.inset.toptrailing.filled
rectangle.leadinghalf.filled
rectangle.leadinghalf.inset.filled
rectangle.leadinghalf.inset.filled.arrow.leading
rectangle.leadingthird.inset.filled
rectangle.lefthalf.fill
rectangle.lefthalf.filled
rectangle.lefthalf.inset.fill
rectangle.lefthalf.inset.fill.arrow.left
rectangle.lefthalf.inset.filled
rectangle.lefthalf.inset.filled.arrow.left
rectangle.leftthird.inset.fill
rectangle.leftthird.inset.filled
rectangle.on.rectangle
rectangle.on.rectangle.angled
rectangle.on.rectangle.badge.gearshape
rectangle.on.rectangle.button.angledtop.vertical.left
rectangle.on.rectangle.button.angledtop.vertical.left.fill
rectangle.on.rectangle.circle.fill
rectangle.on.rectangle.dashed
rectangle.on.rectangle.slash
rectangle.on.rectangle.slash.circle.fill
rectangle.on.rectangle.slash.fill
rectangle.on.rectangle.square
rectangle.on.rectangle.square.fill
rectangle.pattern.checkered
rectangle.portrait.and.arrow.forward
rectangle.portrait.and.arrow.forward.fill
rectangle.portrait.and.arrow.right
rectangle.portrait.and.arrow.right.fill
rectangle.portrait.arrowtriangle.2.inward
rectangle.portrait.arrowtriangle.2.outward
rectangle.portrait.badge.plus
rectangle.portrait.badge.plus.fill
rectangle.portrait.bottomhalf.filled
rectangle.portrait.bottomhalf.inset.filled
rectangle.portrait.bottomleading.inset.filled
rectangle.portrait.bottomleft.inset.filled
rectangle.portrait.bottomright.inset.filled
rectangle.portrait.bottomthird.inset.filled
rectangle.portrait.bottomtrailing.inset.filled
rectangle.portrait.center.inset.filled
rectangle.portrait.inset.filled
rectangle.portrait.leadinghalf.inset.filled
rectangle.portrait.leadingthird.inset.filled
rectangle.portrait.lefthalf.filled
rectangle.portrait.lefthalf.inset.filled
rectangle.portrait.leftthird.inset.filled
rectangle.portrait.on.rectangle.portrait
rectangle.portrait.on.rectangle.portrait.angled
rectangle.portrait.on.rectangle.portrait.angled.fill
rectangle.portrait.on.rectangle.portrait.fill
rectangle.portrait.on.rectangle.portrait.slash
rectangle.portrait.on.rectangle.portrait.slash.fill
rectangle.portrait.righthalf.filled
rectangle.portrait.righthalf.inset.filled
rectangle.portrait.rightthird.inset.filled
rectangle.portrait.slash
rectangle.portrait.slash.fill
rectangle.portrait.split.2x1
rectangle.portrait.split.2x1.fill
rectangle.portrait.split.2x1.slash
rectangle.portrait.split.2x1.slash.fill
rectangle.portrait.tophalf.filled
rectangle.portrait.tophalf.inset.filled
rectangle.portrait.topleading.inset.filled
rectangle.portrait.topleft.inset.filled
rectangle.portrait.topright.inset.filled
rectangle.portrait.topthird.inset.filled
rectangle.portrait.toptrailing.inset.filled
rectangle.portrait.trailinghalf.inset.filled
rectangle.portrait.trailingthird.inset.filled
rectangle.ratio.16.to.9
rectangle.ratio.16.to.9.fill
rectangle.ratio.3.to.4
rectangle.ratio.3.to.4.fill
rectangle.ratio.4.to.3
rectangle.ratio.4.to.3.fill
rectangle.ratio.9.to.16
rectangle.ratio.9.to.16.fill
rectangle.righthalf.fill
rectangle.righthalf.filled
rectangle.righthalf.inset.fill
rectangle.righthalf.inset.fill.arrow.right
rectangle.righthalf.inset.filled
rectangle.righthalf.inset.filled.arrow.right
rectangle.rightthird.inset.fill
rectangle.rightthird.inset.filled
rectangle.roundedbottom
rectangle.roundedbottom.fill
rectangle.roundedtop
rectangle.roundedtop.fill
rectangle.slash
rectangle.slash.fill
rectangle.split.1x2
rectangle.split.1x2.fill
rectangle.split.2x1
rectangle.split.2x1.fill
rectangle.split.2x1.slash
rectangle.split.2x1.slash.fill
rectangle.split.2x2
rectangle.split.2x2.fill
rectangle.split.3x1
rectangle.split.3x1.fill
rectangle.split.3x3
rectangle.split.3x3.fill
rectangle.stack
rectangle.stack.badge.minus
rectangle.stack.badge.person.crop
rectangle.stack.badge.person.crop.fill
rectangle.stack.badge.play
rectangle.stack.badge.play.fill
rectangle.stack.badge.plus
rectangle.stack.fill
rectangle.stack.fill.badge.minus
rectangle.stack.fill.badge.person.crop
rectangle.stack.fill.badge.plus
rectangle.stack.person.crop
rectangle.stack.person.crop.fill
rectangle.stack.slash
rectangle.stack.slash.fill
rectangle.tophalf.filled
rectangle.tophalf.inset.filled
rectangle.topthird.inset
rectangle.topthird.inset.fill
rectangle.topthird.inset.filled
rectangle.trailinghalf.filled
rectangle.trailinghalf.inset.filled
rectangle.trailinghalf.inset.filled.arrow.trailing
rectangle.trailingthird.inset.filled
refrigerator
refrigerator.fill
repeat.badge.xmark.circle.fill
restart
restart.circle.fill
richtext.page
richtext.page.fill
right
right.circle.fill
righttriangle
righttriangle.fill
righttriangle.split.diagonal
righttriangle.split.diagonal.fill
rm.button.horizontal
rm.button.horizontal.fill
robotic.vacuum
robotic.vacuum.and.arrowtriangle.up
robotic.vacuum.and.arrowtriangle.up.fill
robotic.vacuum.fill
roller.shade.closed
roller.shade.open
roman.shade.closed
roman.shade.open
rosette
rotate.3d
rotate.3d.circle.fill
rotate.3d.fill
rotate.left
rotate.left.fill
rotate.right
rotate.right.fill
rsb.button.angledbottom.horizontal.right
rsb.button.angledbottom.horizontal.right.fill
rt.button.roundedtop.horizontal
rt.button.roundedtop.horizontal.fill
rt.circle.fill
rt.rectangle.roundedtop
rt.rectangle.roundedtop.fill
rublesign.arrow.circlepath
rublesign.bank.building
rublesign.bank.building.fill
rugbyball
rugbyball.circle.fill
rugbyball.fill
ruler
ruler.fill
rupeesign.arrow.circlepath
rupeesign.bank.building
rupeesign.bank.building.fill
safari
safari.fill
sailboat
sailboat.circle.fill
sailboat.fill
scale.3d
scalemass
scalemass.fill
scissors
scissors.badge.ellipsis
scissors.circle.fill
scooter
scope
screwdriver
screwdriver.fill
scribble
scribble.variable
scroll
scroll.fill
sdcard
sdcard.fill
selection.pin.in.out
service.dog
service.dog.fill
shared.with.you
shared.with.you.circle
shared.with.you.circle.fill
shared.with.you.slash
sharedwithyou
sharedwithyou.circle.fill
sharedwithyou.slash
shareplay.slash
shazam.logo
shazam.logo.fill
shekelsign.arrow.circlepath
shekelsign.bank.building
shekelsign.bank.building.fill
sheqelsign.circle
sheqelsign.circle.fill
sheqelsign.square
sheqelsign.square.fill
shield.checkerboard
shield.checkered
shield.lefthalf.fill
shield.lefthalf.fill.slash
shield.lefthalf.filled
shield.lefthalf.filled.badge.checkmark
shield.lefthalf.filled.slash
shield.lefthalf.filled.trianglebadge.exclamationmark
shield.pattern.checkered
shield.righthalf.filled
shield.slash
shield.slash.fill
shippingbox
shippingbox.and.arrow.backward
shippingbox.and.arrow.backward.fill
shippingbox.circle.fill
shippingbox.fill
shoe
shoe.2
shoe.2.fill
shoe.circle.fill
shoe.fill
shoeprints.fill
sidebar.leading
sidebar.left
sidebar.right
sidebar.squares.leading
sidebar.squares.left
sidebar.squares.right
sidebar.squares.trailing
sidebar.trailing
signpost.and.arrowtriangle.up
signpost.and.arrowtriangle.up.circle.fill
signpost.and.arrowtriangle.up.fill
signpost.left
signpost.left.circle.fill
signpost.left.fill
signpost.right
signpost.right.and.left
signpost.right.and.left.circle.fill
signpost.right.and.left.fill
signpost.right.circle.fill
signpost.right.fill
simcard
simcard.2
simcard.2.fill
simcard.fill
singaporedollarsign.bank.building
singaporedollarsign.bank.building.fill
sink
sink.fill
siri
skateboard
skateboard.fill
skew
skis
skis.fill
slash.circle.fill
sleep
sleep.circle.fill
slider.horizontal.2.gobackward
slider.horizontal.2.rectangle.and.arrow.triangle.2.circlepath
slider.horizontal.2.rectangle.and.arrow.trianglehead.2.clockwise.rotate.90
slider.horizontal.2.square
slider.horizontal.2.square.badge.arrow.down
slider.horizontal.2.square.on.square
slider.horizontal.3
slider.horizontal.below.circle.lefthalf.filled
slider.horizontal.below.circle.lefthalf.filled.inverse
slider.horizontal.below.circle.righthalf.filled
slider.horizontal.below.circle.righthalf.filled.inverse
slider.horizontal.below.rectangle
slider.horizontal.below.square.and.square.filled
slider.horizontal.below.square.fill.and.square
slider.horizontal.below.square.filled.and.square
slider.horizontal.below.sun.max
slider.horizontal.below.sun.min
slider.vertical.3
smallcircle.circle.fill
smallcircle.fill.circle
smallcircle.fill.circle.fill
smallcircle.filled.circle.fill
smiley
smiley.fill
smoke
smoke.circle.fill
smoke.fill
snow
snowboard
snowboard.fill
soccerball
soccerball.circle.fill
soccerball.circle.fill.inverse
soccerball.circle.inverse
soccerball.inverse
sofa
sofa.fill
sos
sos.circle.fill
sparkle
sparkle.magnifyingglass
sparkle.text.clipboard
sparkle.text.clipboard.fill
sparkles
sparkles.2
sparkles.rectangle.stack
sparkles.rectangle.stack.fill
sparkles.square.fill.on.square
sparkles.square.filled.on.square
spatial.capture
spatial.capture.fill
spatial.capture.on.hexagon
spatial.capture.on.hexagon.fill
spatial.capture.slash
spatial.capture.slash.fill
speaker
speaker.1
speaker.1.fill
speaker.2
speaker.2.fill
speaker.3
speaker.3.fill
speaker.badge.exclamationmark
speaker.badge.exclamationmark.fill
speaker.circle.fill
speaker.fill
speaker.minus
speaker.minus.fill
speaker.plus
speaker.plus.fill
speaker.slash
speaker.slash.circle.fill
speaker.slash.fill
speaker.square
speaker.square.fill
speaker.trianglebadge.exclamationmark
speaker.trianglebadge.exclamationmark.fill
speaker.wave.2.bubble.left
speaker.wave.2.bubble.left.fill
speaker.zzz
speaker.zzz.fill
speedometer
spigot
spigot.fill
spoon.serving
sportscourt
sportscourt.circle.fill
sportscourt.fill
sprinkler
sprinkler.fill
square.2.layers.3d
square.2.layers.3d.bottom.filled
square.2.layers.3d.fill
square.2.layers.3d.top.filled
square.2.stack.3d
square.2.stack.3d.bottom.fill
square.2.stack.3d.bottom.filled
square.2.stack.3d.top.fill
square.2.stack.3d.top.filled
square.3.layers.3d.bottom.filled
square.3.layers.3d.down.left.slash
square.3.layers.3d.down.right.slash
square.3.layers.3d.middle.filled
square.3.layers.3d.slash
square.3.layers.3d.top.filled
square.3.stack.3d
square.3.stack.3d.bottom.fill
square.3.stack.3d.bottom.filled
square.3.stack.3d.middle.fill
square.3.stack.3d.middle.filled
square.3.stack.3d.slash
square.3.stack.3d.top.fill
square.3.stack.3d.top.filled
square.and.arrow.down
square.and.arrow.down.badge.checkmark
square.and.arrow.down.badge.checkmark.fill
square.and.arrow.down.badge.clock
square.and.arrow.down.badge.clock.fill
square.and.arrow.down.badge.xmark
square.and.arrow.down.badge.xmark.fill
square.and.arrow.down.fill
square.and.arrow.down.on.square
square.and.arrow.down.on.square.fill
square.and.arrow.up
square.and.arrow.up.badge.checkmark
square.and.arrow.up.badge.checkmark.fill
square.and.arrow.up.badge.clock
square.and.arrow.up.badge.clock.fill
square.and.arrow.up.circle.fill
square.and.arrow.up.fill
square.and.arrow.up.on.square
square.and.arrow.up.on.square.fill
square.and.arrow.up.trianglebadge.exclamationmark
square.and.arrow.up.trianglebadge.exclamationmark.fill
square.and.at.rectangle
square.and.at.rectangle.fill
square.and.line.vertical.and.square
square.and.line.vertical.and.square.fill
square.and.line.vertical.and.square.filled
square.and.pencil
square.and.pencil.circle.fill
square.arrowtriangle.4.outward
square.badge.plus
square.badge.plus.fill
square.bottomhalf.fill
square.bottomhalf.filled
square.bottomthird.inset.filled
square.circle.fill
square.dashed
square.dashed.inset.fill
square.dashed.inset.filled
square.dotted
square.fill.and.line.vertical.and.square
square.fill.and.line.vertical.and.square.fill
square.fill.and.line.vertical.square.fill
square.fill.on.circle.fill
square.fill.on.square
square.fill.on.square.fill
square.filled.and.line.vertical.and.square
square.filled.on.square
square.grid.2x2
square.grid.2x2.fill
square.grid.3x1.below.line.grid.1x2
square.grid.3x1.below.line.grid.1x2.fill
square.grid.3x1.fill.below.line.grid.1x2
square.grid.3x1.folder.badge.plus
square.grid.3x1.folder.fill.badge.plus
square.grid.3x2
square.grid.3x2.fill
square.grid.3x3
square.grid.3x3.bottomleft.fill
square.grid.3x3.bottomleft.filled
square.grid.3x3.bottommiddle.fill
square.grid.3x3.bottommiddle.filled
square.grid.3x3.bottomright.fill
square.grid.3x3.bottomright.filled
square.grid.3x3.fill
square.grid.3x3.fill.square
square.grid.3x3.middle.fill
square.grid.3x3.middle.filled
square.grid.3x3.middleleft.fill
square.grid.3x3.middleleft.filled
square.grid.3x3.middleright.fill
square.grid.3x3.middleright.filled
square.grid.3x3.square
square.grid.3x3.square.badge.ellipsis
square.grid.3x3.topleft.fill
square.grid.3x3.topleft.filled
square.grid.3x3.topmiddle.fill
square.grid.3x3.topmiddle.filled
square.grid.3x3.topright.fill
square.grid.3x3.topright.filled
square.grid.4x3.fill
square.inset.filled
square.leadingthird.inset.filled
square.lefthalf.fill
square.lefthalf.filled
square.leftthird.inset.filled
square.on.circle
square.on.square
square.on.square.badge.person.crop
square.on.square.badge.person.crop.fill
square.on.square.dashed
square.on.square.intersection.dashed
square.on.square.squareshape.controlhandles
square.resize
square.resize.down
square.resize.up
square.righthalf.fill
square.righthalf.filled
square.rightthird.inset.filled
square.slash
square.slash.fill
square.split.1x2
square.split.1x2.fill
square.split.2x1
square.split.2x1.fill
square.split.2x2
square.split.2x2.fill
square.split.bottomrightquarter
square.split.bottomrightquarter.fill
square.split.diagonal
square.split.diagonal.2x2
square.split.diagonal.2x2.fill
square.split.diagonal.fill
square.stack
square.stack.3d.down.dottedline
square.stack.3d.up.badge.a
square.stack.3d.up.badge.a.fill
square.stack.3d.up.slash
square.stack.3d.up.slash.fill
square.stack.fill
square.text.square
square.text.square.fill
square.tophalf.fill
square.tophalf.filled
square.topthird.inset.filled
square.trailingthird.inset.filled
squares.below.rectangle
squares.leading.rectangle
squares.leading.rectangle.fill
squareshape
squareshape.controlhandles.on.squareshape.controlhandles
squareshape.dashed.squareshape
squareshape.dotted.split.2x2
squareshape.dotted.squareshape
squareshape.fill
squareshape.split.2x2
squareshape.split.2x2.dotted
squareshape.split.2x2.dotted.inside
squareshape.split.2x2.dotted.inside.and.outside
squareshape.split.2x2.dotted.outside
squareshape.split.3x3
squareshape.squareshape.dashed
squareshape.squareshape.dotted
stairs
star
star.bubble
star.bubble.fill
star.circle.fill
star.fill
star.leadinghalf.fill
star.leadinghalf.filled
star.lefthalf.fill
star.rectangle
star.rectangle.fill
star.slash
star.slash.fill
star.square
star.square.fill
star.square.on.square
star.square.on.square.fill
staroflife
staroflife.circle.fill
staroflife.fill
staroflife.shield
staroflife.shield.fill
steeringwheel.and.lock
sterlingsign.arrow.circlepath
sterlingsign.bank.building
sterlingsign.bank.building.fill
stethoscope
stethoscope.circle.fill
stopwatch
stopwatch.fill
storefront
storefront.circle.fill
storefront.fill
stove
stove.fill
stroke.line.diagonal
stroke.line.diagonal.slash
stroller
stroller.fill
studentdesk
suit.club
suit.club.fill
suit.diamond
suit.diamond.fill
suit.heart
suit.heart.fill
suit.spade
suit.spade.fill
suitcase
suitcase.cart
suitcase.cart.fill
suitcase.circle.fill
suitcase.fill
suitcase.rolling
suitcase.rolling.and.film
suitcase.rolling.and.film.circle.fill
suitcase.rolling.and.film.fill
suitcase.rolling.and.suitcase
suitcase.rolling.and.suitcase.circle.fill
suitcase.rolling.and.suitcase.fill
suitcase.rolling.circle.fill
suitcase.rolling.fill
sun.and.horizon
sun.and.horizon.circle
sun.and.horizon.circle.fill
sun.and.horizon.fill
sun.dust
sun.dust.circle.fill
sun.dust.fill
sun.haze
sun.haze.circle.fill
sun.haze.fill
sun.horizon
sun.horizon.circle.fill
sun.horizon.fill
sun.lefthalf.filled
sun.max.trianglebadge.exclamationmark
sun.max.trianglebadge.exclamationmark.fill
sun.rain
sun.rain.circle.fill
sun.rain.fill
sun.righthalf.filled
sun.snow
sun.snow.circle.fill
sun.snow.fill
sunglasses
sunglasses.fill
sunrise
sunrise.circle.fill
sunrise.fill
sunset
sunset.circle.fill
sunset.fill
surfboard
surfboard.fill
swatchpalette
swatchpalette.fill
swedishkronasign.arrow.circlepath
swedishkronasign.bank.building
swedishkronasign.bank.building.fill
swift
swiftdata
swirl.circle.righthalf.filled
swirl.circle.righthalf.filled.inverse
switch.2
switch.programmable
switch.programmable.fill
switch.programmable.square
switch.programmable.square.fill
syringe
syringe.fill
t.bubble
t.bubble.fill
table
table.badge.more
table.badge.more.fill
table.fill
table.furniture
table.furniture.fill
tablecells
tablecells.badge.ellipsis
tablecells.badge.ellipsis.fill
tablecells.fill
tablecells.fill.badge.ellipsis
tag
tag.circle.fill
tag.fill
tag.slash
tag.slash.fill
tag.square
tag.square.fill
takeoutbag.and.cup.and.straw
takeoutbag.and.cup.and.straw.fill
teddybear
teddybear.fill
teletype
teletype.answer
teletype.answer.circle.fill
teletype.circle.fill
tengesign.arrow.circlepath
tengesign.bank.building
tengesign.bank.building.fill
tennis.racket
tennis.racket.circle.fill
tennisball
tennisball.circle.fill
tennisball.fill
tent
tent.2
tent.2.circle.fill
tent.2.fill
tent.circle.fill
tent.fill
terminal
terminal.fill
testtube.2
text.and.command.macwindow
text.badge.checkmark
text.badge.minus
text.badge.plus
text.badge.star
text.badge.xmark
text.below.folder
text.below.folder.fill
text.below.photo
text.below.photo.fill
text.book.closed
text.book.closed.fill
text.bubble
text.bubble.badge.clock
text.bubble.badge.clock.fill
text.bubble.fill
text.cursor
text.document
text.document.fill
text.justifyleft
text.justifyright
text.magnifyingglass
text.pad.header
text.pad.header.badge.clock
text.pad.header.badge.plus
text.page
text.page.badge.magnifyingglass
text.page.fill
text.page.slash
text.page.slash.fill
text.quote
text.rectangle
text.rectangle.fill
text.rectangle.page
text.rectangle.page.fill
text.viewfinder
textbox
textformat.12
textformat.12.km
textformat.12.my
textformat.123
textformat.abc
textformat.abc.dottedunderline
theatermask.and.paintbrush
theatermask.and.paintbrush.fill
theatermasks
theatermasks.circle.fill
theatermasks.fill
thermometer
thermometer.snowflake.circle.fill
thermometer.sun.circle.fill
thermometer.variable
thermometer.variable.and.figure
thermometer.variable.and.figure.circle.fill
thermometer.variable.badge.clock
thermometer.variable.badge.play
ticket
ticket.circle.fill
ticket.fill
timeline.selection
timer
timer.circle.fill
timer.square
togglepower
toilet
toilet.circle.fill
toilet.fill
tornado
tornado.circle.fill
tortoise
tortoise.circle.fill
tortoise.fill
torus
train.side.front.car
train.side.middle.car
train.side.rear.car
tram
tram.card
tram.card.fill
tram.circle.fill
tram.fill
tram.fill.tunnel
tram.tunnel.fill
translate
trapezoid.and.line.horizontal
trapezoid.and.line.horizontal.fill
trapezoid.and.line.vertical
trapezoid.and.line.vertical.fill
trash
trash.circle.fill
trash.fill
trash.slash
trash.slash.circle.fill
trash.slash.fill
trash.slash.square
trash.slash.square.fill
trash.square
trash.square.fill
tray
tray.2
tray.2.fill
tray.and.arrow.down
tray.and.arrow.down.fill
tray.and.arrow.up
tray.and.arrow.up.fill
tray.badge
tray.badge.fill
tray.circle.fill
tray.fill
tray.full
tray.full.fill
tree
tree.circle.fill
tree.fill
triangle.bottomhalf.filled
triangle.circle.fill
triangle.inset.filled
triangle.lefthalf.fill
triangle.lefthalf.filled
triangle.righthalf.fill
triangle.righthalf.filled
triangle.tophalf.filled
trophy
trophy.circle.fill
trophy.fill
tropicalstorm
tropicalstorm.circle.fill
truck.box
truck.box.badge.clock
truck.box.badge.clock.fill
truck.box.fill
tshirt
tshirt.circle.fill
tshirt.fill
tugriksign.arrow.circlepath
tugriksign.bank.building
tugriksign.bank.building.fill
tuningfork
turkishlirasign.arrow.circlepath
turkishlirasign.bank.building
turkishlirasign.bank.building.fill
tv.inset.filled
tv.music.note
tv.music.note.fill
uiwindow.split.2x1
umbrella
umbrella.circle.fill
umbrella.fill
umbrella.percent
umbrella.percent.fill
vial.viewfinder
video
video.and.waveform
video.and.waveform.fill
video.badge.checkmark
video.badge.ellipsis
video.badge.plus
video.badge.plus.fill
video.bubble
video.bubble.fill
video.bubble.left
video.bubble.left.fill
video.circle.fill
video.doorbell
video.doorbell.fill
video.fill
video.fill.badge.checkmark
video.fill.badge.ellipsis
video.fill.badge.plus
video.slash
video.slash.circle.fill
video.slash.fill
video.square
video.square.fill
videoprojector
videoprojector.fill
view.2d
view.3d
viewfinder.circle.fill
viewfinder.rectangular
viewfinder.trianglebadge.exclamationmark
visionpro
visionpro.and.arrow.forward
visionpro.and.arrow.forward.fill
visionpro.badge.exclamationmark
visionpro.badge.exclamationmark.fill
visionpro.badge.play
visionpro.badge.play.fill
visionpro.circle
visionpro.circle.fill
visionpro.fill
visionpro.slash
visionpro.slash.circle
visionpro.slash.circle.fill
visionpro.slash.fill
voiceover
volleyball
volleyball.circle.fill
volleyball.fill
wake
wake.circle.fill
wallet.bifold
wallet.bifold.fill
wallet.pass
wallet.pass.fill
wand.and.outline
wand.and.outline.inverse
wand.and.sparkles
wand.and.sparkles.inverse
wand.and.stars
wand.and.stars.inverse
washer
washer.circle.fill
washer.fill
watch.analog
water.waves.and.arrow.down
water.waves.and.arrow.down.trianglebadge.exclamationmark
water.waves.and.arrow.up
water.waves.slash
waterbottle
waterbottle.fill
waveform.and.magnifyingglass
waveform.and.mic
waveform.and.person.filled
waveform.badge.mic
waveform.path
waveform.path.badge.minus
waveform.path.badge.plus
waveform.path.ecg
waveform.path.ecg.magnifyingglass
waveform.path.ecg.rectangle
waveform.path.ecg.rectangle.fill
waveform.path.ecg.text
waveform.path.ecg.text.clipboard
waveform.path.ecg.text.clipboard.fill
waveform.path.ecg.text.page
waveform.path.ecg.text.page.fill
web.camera
web.camera.fill
wheelchair
widget.extralarge
widget.extralarge.badge.plus
widget.large
widget.large.badge.plus
widget.medium
widget.medium.badge.plus
widget.small
widget.small.badge.plus
wifi.exclamationmark
wifi.exclamationmark.circle.fill
wifi.slash
wind
wind.circle.fill
wind.snow
wind.snow.circle.fill
window.awning
window.awning.closed
window.casement
window.casement.closed
window.ceiling
window.ceiling.closed
window.horizontal
window.horizontal.closed
window.shade.closed
window.shade.open
window.vertical.closed
window.vertical.open
windshield.front.and.fluid
windshield.rear.and.fluid
wineglass
wineglass.fill
wonsign.arrow.circlepath
wonsign.bank.building
wonsign.bank.building.fill
wrench
wrench.adjustable
wrench.adjustable.fill
wrench.and.screwdriver
wrench.and.screwdriver.fill
wrench.fill
x.squareroot
xbox.logo
xmark
xmark.app
xmark.app.fill
xmark.bin
xmark.bin.circle.fill
xmark.bin.fill
xmark.circle.badge.airplane
xmark.circle.badge.airplane.fill
xmark.circle.fill
xmark.diamond
xmark.diamond.fill
xmark.icloud
xmark.icloud.fill
xmark.octagon
xmark.octagon.fill
xmark.rectangle
xmark.rectangle.fill
xmark.rectangle.portrait
xmark.rectangle.portrait.fill
xmark.seal
xmark.seal.fill
xmark.shield
xmark.shield.fill
xmark.square
xmark.square.fill
yensign.arrow.circlepath
yensign.bank.building
yensign.bank.building.fill
zipper.page
zl.button.roundedtop.horizontal
zl.button.roundedtop.horizontal.fill
zl.rectangle.roundedtop
zl.rectangle.roundedtop.fill
zr.button.roundedtop.horizontal
zr.button.roundedtop.horizontal.fill
zr.rectangle.roundedtop
zr.rectangle.roundedtop.fill
zzz
"""
}
