#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Append batch-2 expansion rows to ai_tech_brands_seed.tsv with deduplication."""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SEED_PATH = REPO_ROOT / "Scripts/lexicon/seeds/ai_tech_brands_seed.tsv"

# word, pinyin, aliases (| separated), category, weight
EXPANSION: list[tuple[str, str, str, str, int]] = [
    # --- AI brands / models / agents ---
    ("NanoClaw", "", "nano claw|Nano Claw", "ai_brand", 86),
    ("ZeroClaw", "", "zero claw|Zero Claw", "ai_brand", 82),
    ("Hermes Agent", "", "hermes agent|Hermes", "ai_brand", 84),
    ("Fugu", "", "sakana fugu|Fugu AI", "ai_brand", 84),
    ("Sakana AI", "", "sakana ai|Sakana", "ai_brand", 82),
    ("Agents-A1", "", "agents a1|Agents A1", "ai_model", 82),
    ("NemoClaw", "", "nemo claw|Nemo Claw", "ai_brand", 80),
    ("Moltworker", "", "molt worker|Moltworker", "ai_platform", 78),
    ("Perplexity Computer", "", "perplexity computer|Personal Computer", "ai_brand", 84),
    ("Personal Computer", "", "perplexity personal computer", "ai_brand", 82),
    ("Simular", "", "simular ai|Simular AI", "ai_brand", 78),
    ("Vellum", "", "vellum ai|Vellum AI", "ai_platform", 78),
    ("Cloudflare Agents", "", "cloudflare agents", "ai_platform", 78),
    ("NVIDIA NIM", "", "nvidia nim|NIM inference", "ai_platform", 82),
    ("Fireworks AI", "", "fireworks ai|Fireworks", "ai_platform", 82),
    ("Together AI", "", "together ai|Together", "ai_platform", 82),
    ("Cerebras", "", "cerebras systems|Cerebras Systems", "tech_company", 82),
    ("SambaNova", "", "samba nova|Samba Nova", "tech_company", 80),
    ("Grokipedia", "", "grok ipedia|Grok pedia", "ai_brand", 76),
    ("Grok Imagine", "", "grok imagine", "ai_brand", 78),
    ("Imagen", "", "google imagen|Imagen AI", "ai_model", 82),
    ("Veo", "", "google veo|Veo AI", "ai_model", 82),
    ("Suno", "", "suno ai|Suno AI", "ai_brand", 84),
    ("Udio", "", "udio ai|Udio AI", "ai_brand", 82),
    ("Flux", "", "black forest flux|FLUX", "ai_model", 84),
    ("Black Forest Labs", "", "black forest labs|BFL", "ai_brand", 82),
    ("Ideogram", "", "ideogram ai|Ideogram AI", "ai_brand", 80),
    ("Recraft", "", "recraft ai|Recraft AI", "ai_brand", 78),
    ("Leonardo AI", "", "leonardo ai|Leonardo", "ai_brand", 80),
    ("Krea", "", "krea ai|Krea AI", "ai_brand", 76),
    ("PixVerse", "", "pix verse|Pixverse", "ai_brand", 80),
    ("Vidu", "", "vidu ai|Vidu AI", "ai_brand", 80),
    ("可灵AI", "ke ling AI", "Kling AI|可灵", "ai_brand", 84),
    ("通义万相", "tong yi wan xiang", "Wanxiang|万相", "ai_brand", 84),
    ("Wanxiang", "", "通义万相|wan xiang", "ai_brand", 82),
    ("海螺视频", "hai luo shi pin", "Hailuo Video", "ai_brand", 80),
    ("Skywork", "", "skywork ai|Skywork", "ai_brand", 78),
    ("天工AI", "tian gong AI", "天工", "ai_brand", 78),
    ("纳米搜索", "na mi sou suo", "Nami Search", "ai_brand", 76),
    ("Flowith", "", "flowith ai|Flowith AI", "ai_platform", 76),
    ("FlowGPT", "", "flow gpt|Flow GPT", "ai_platform", 74),
    ("Coze", "", "coze ai|扣子", "ai_platform", 86),
    ("扣子", "kou zi", "Coze|coze", "ai_platform", 84),
    ("Dify", "", "dify ai|Dify AI", "ai_platform", 84),
    ("FastGPT", "", "fast gpt|FastGPT", "ai_platform", 78),
    ("MaxKB", "", "max kb|MaxKB", "ai_platform", 76),
    ("RAGFlow", "", "rag flow|RAGFlow", "ai_platform", 82),
    ("Mem0", "", "mem zero|Mem0 AI", "ai_platform", 80),
    ("Letta", "", "letta ai|Letta AI", "ai_platform", 78),
    ("Zep", "", "zep ai|Zep AI", "ai_platform", 76),
    ("GraphRAG", "", "graph rag|Graph RAG", "ai_term", 84),
    ("LightRAG", "", "light rag|Light RAG", "ai_term", 82),
    ("Devstral", "", "devstral|mistral devstral", "ai_model", 82),
    ("Pixtral", "", "pixtral|mistral pixtral", "ai_model", 82),
    ("Mistral Small", "", "mistral small", "ai_model", 80),
    ("Mistral Codestral", "", "mistral codestral", "ai_model", 82),
    ("Codestral", "", "codestral|mistral codestral", "ai_model", 84),
    ("Command R", "", "command r|cohere command", "ai_model", 80),
    ("Cohere Command", "", "cohere command|Command R", "ai_model", 78),
    ("Phi", "", "phi model|microsoft phi", "ai_model", 78),
    ("Phi模型", "phi mo xing", "Phi|microsoft phi", "ai_model", 76),
    ("Granite", "", "ibm granite|Granite model", "ai_model", 80),
    ("IBM Granite", "", "granite|IBM Granite", "ai_model", 78),
    ("Amazon Nova", "", "amazon nova|Nova model", "ai_model", 82),
    ("Bedrock", "", "aws bedrock|Amazon Bedrock", "ai_platform", 82),
    ("Gemma开源", "gemma kai yuan", "Gemma open", "ai_model", 76),
    ("Claude Mythos", "", "claude mythos|Mythos", "ai_model", 82),
    ("Whisper", "", "openai whisper|Whisper ASR", "ai_model", 82),
    ("NotebookLM", "", "notebook lm|Notebook LM", "ai_brand", 84),
    ("Google AI Studio", "", "google ai studio|AI Studio", "dev_tool", 82),
    ("AI Studio", "", "google ai studio", "dev_tool", 80),
    ("Gemini Live", "", "gemini live", "ai_brand", 80),
    ("Gemini Robotics", "", "gemini robotics", "ai_brand", 78),
    ("Apple Intelligence", "", "apple intelligence|苹果智能", "ai_brand", 86),
    ("苹果智能", "ping guo zhi neng", "Apple Intelligence", "ai_brand", 84),
    ("Siri", "", "apple siri|Siri AI", "ai_brand", 82),
    ("Writing Tools", "", "apple writing tools", "ai_term", 76),
    ("Image Playground", "", "image playground|苹果图像游乐场", "ai_term", 74),
    ("Copilot Studio", "", "copilot studio|Microsoft Copilot Studio", "ai_platform", 80),
    ("Microsoft Agent", "", "microsoft agent", "ai_platform", 78),
    ("Semantic Kernel", "", "semantic kernel|SK", "ai_platform", 80),
    ("AutoGen Studio", "", "autogen studio|AutoGen Studio", "ai_platform", 78),
    ("Windsurf Cascade", "", "windsurf cascade|Cascade", "dev_tool", 82),
    ("Cascade", "", "windsurf cascade", "dev_tool", 80),
    ("Tabnine", "", "tab nine|Tabnine", "dev_tool", 80),
    ("Sourcegraph Cody", "", "sourcegraph cody|Cody", "dev_tool", 82),
    ("Cody", "", "sourcegraph cody", "dev_tool", 78),
    ("GitHub Spark", "", "github spark|Spark", "dev_tool", 78),
    ("GitHub Models", "", "github models", "ai_platform", 78),
    ("Browser Use", "", "browser use|browser-use", "ai_term", 84),
    ("Augment", "", "augment code|Augment Code", "dev_tool", 80),
    ("JetBrains Junie", "", "jetbrains junie|Junie", "dev_tool", 78),
    ("Kilo Code", "", "kilo code|KiloCode", "dev_tool", 78),
    ("Zencoder", "", "zen coder|Zencoder", "dev_tool", 76),
    ("Goose", "", "goose ai|Block Goose", "dev_tool", 76),
    ("Omnigent", "", "omnigent ai|Omnigent", "dev_tool", 74),
    # --- Entrepreneurs / internet figures ---
    ("俞敏洪", "yu min hong", "Yu Minhong|新东方俞敏洪", "tech_leader", 86),
    ("Yu Minhong", "", "yu minhong|俞敏洪", "tech_leader", 84),
    ("New Oriental", "", "new oriental|新东方", "tech_company", 80),
    ("新东方", "xin dong fang", "New Oriental", "tech_company", 80),
    ("卢伟冰", "lu wei bing", "Lu Weibing", "tech_leader", 84),
    ("Lu Weibing", "", "lu weibing|卢伟冰", "tech_leader", 84),
    ("影视飓风", "ying shi ju feng", "影视飓风Tim", "tech_leader", 82),
    ("影视飓风Tim", "", "ying shi ju feng tim|影视飓风", "tech_leader", 82),
    ("曹德旺", "cao de wang", "Cao Dewang", "tech_leader", 80),
    ("Cao Dewang", "", "cao dewang|曹德旺", "tech_leader", 80),
    ("福耀玻璃", "fu yao bo li", "Fuyao Glass", "tech_company", 76),
    ("宗庆后", "zong qing hou", "Zong Qinghou", "tech_leader", 78),
    ("钟睒睒", "zhong shan shan", "Zhong Shanshan", "tech_leader", 80),
    ("Nongfu Spring", "", "nongfu spring|农夫山泉", "consumer_brand", 82),
    ("农夫山泉", "nong fu shan quan", "Nongfu Spring", "consumer_brand", 82),
    ("王健林", "wang jian lin", "Wang Jianlin", "tech_leader", 78),
    ("Wang Jianlin", "", "wang jianlin|王健林", "tech_leader", 78),
    ("许家印", "xu jia yin", "Xu Jiayin", "tech_leader", 74),
    ("Xu Jiayin", "", "xu jiayin|许家印", "tech_leader", 74),
    ("孙正义", "sun zheng yi", "Masayoshi Son", "tech_leader", 82),
    ("Masayoshi Son", "", "masayoshi son|孙正义", "tech_leader", 82),
    ("张朝阳", "zhang chao yang", "Charles Zhang", "tech_leader", 80),
    ("Charles Zhang", "", "charles zhang|张朝阳", "tech_leader", 80),
    ("搜狐", "sou hu", "Sohu", "tech_company", 78),
    ("Sohu", "", "sohu|搜狐", "tech_company", 78),
    ("丁磊", "ding lei", "William Ding", "tech_leader", 84),
    ("William Ding", "", "william ding|丁磊", "tech_leader", 84),
    ("陈天桥", "chen tian qiao", "Chen Tianqiao", "tech_leader", 76),
    ("沈南鹏", "shen nan peng", "Neil Shen", "tech_leader", 82),
    ("Neil Shen", "", "neil shen|沈南鹏", "tech_leader", 82),
    ("红杉中国", "hong shan zhong guo", "Sequoia China", "fintech", 80),
    ("Sequoia China", "", "sequoia china|红杉中国", "fintech", 80),
    ("徐新", "xu xin", "Xu Xin", "tech_leader", 76),
    ("今日资本", "jin ri zi ben", "Capital Today", "fintech", 74),
    ("朱啸虎", "zhu xiao hu", "Zhu Xiaohu", "tech_leader", 78),
    ("李开复", "li kai fu", "Kai-Fu Lee", "tech_leader", 86),
    ("Kai-Fu Lee", "", "kai fu lee|李开复", "tech_leader", 86),
    ("创新工场", "chuang xin gong chang", "Innovation Works", "tech_company", 78),
    ("Innovation Works", "", "innovation works|创新工场", "tech_company", 78),
    ("傅盛", "fu sheng", "Fu Sheng", "tech_leader", 78),
    ("Fu Sheng", "", "fu sheng|傅盛", "tech_leader", 78),
    ("猎豹移动", "lie bao yi dong", "Cheetah Mobile", "tech_company", 76),
    ("王小川", "wang xiao chuan", "Wang Xiaochuan", "tech_leader", 82),
    ("Wang Xiaochuan", "", "wang xiaochuan|王小川", "tech_leader", 82),
    ("周航", "zhou hang", "Zhou Hang", "tech_leader", 72),
    ("陈睿", "chen rui", "Chen Rui|B站陈睿", "tech_leader", 80),
    ("Chen Rui", "", "chen rui|陈睿", "tech_leader", 80),
    ("宿华", "su hua", "Su Hua", "tech_leader", 78),
    ("Su Hua", "", "su hua|宿华", "tech_leader", 78),
    ("程一笑", "cheng yi xiao", "Cheng Yixiao", "tech_leader", 76),
    ("Cheng Yixiao", "", "cheng yixiao|程一笑", "tech_leader", 76),
    ("陈欧", "chen ou", "Chen Ou", "tech_leader", 72),
    ("聚美优品", "ju mei you pin", "Jumei", "tech_company", 70),
    ("江南春", "jiang nan chun", "Jiang Nanchun", "tech_leader", 76),
    ("分众传媒", "fen zhong chuan mei", "Focus Media", "tech_company", 76),
    ("沈晖", "shen hui", "William Feng", "tech_leader", 74),
    ("李想", "li xiang", "Li Xiang|理想李想", "tech_leader", 86),
    ("Li Xiang", "", "li xiang|李想", "tech_leader", 86),
    ("王传福", "wang chuan fu", "Wang Chuanfu", "tech_leader", 86),
    ("Wang Chuanfu", "", "wang chuanfu|王传福", "tech_leader", 86),
    ("曾毓群", "zeng yu qun", "Robin Zeng", "tech_leader", 84),
    ("Robin Zeng", "", "robin zeng|曾毓群", "tech_leader", 84),
    ("郭台铭", "guo tai ming", "Terry Gou", "tech_leader", 80),
    ("Terry Gou", "", "terry gou|郭台铭", "tech_leader", 80),
    ("富士康", "fu shi kang", "Foxconn", "tech_company", 82),
    ("Foxconn", "", "foxconn|富士康", "tech_company", 82),
    ("刘慈欣", "liu ci xin", "Liu Cixin", "celebrity", 82),
    ("Liu Cixin", "", "liu cixin|刘慈欣", "celebrity", 82),
    ("三体", "san ti", "Three Body Problem|Three-Body", "tech_term", 80),
    # --- Celebrities ---
    ("刘宇宁", "liu yu ning", "Liu Yuning", "celebrity", 86),
    ("Liu Yuning", "", "liu yuning|刘宇宁", "celebrity", 86),
    ("梓渝", "zi yu", "Ziyu", "celebrity", 82),
    ("Ziyu", "", "zi yu|梓渝", "celebrity", 82),
    ("周深", "zhou shen", "Zhou Shen", "celebrity", 86),
    ("Zhou Shen", "", "zhou shen|周深", "celebrity", 86),
    ("白鹿", "bai lu", "Bai Lu", "celebrity", 84),
    ("Bai Lu", "", "bai lu|白鹿", "celebrity", 84),
    ("孟子义", "meng zi yi", "Meng Ziyi", "celebrity", 82),
    ("Meng Ziyi", "", "meng ziyi|孟子义", "celebrity", 82),
    ("虞书欣", "yu shu xin", "Esther Yu", "celebrity", 84),
    ("Esther Yu", "", "esther yu|虞书欣", "celebrity", 84),
    ("赵丽颖", "zhao li ying", "Zhao Liying", "celebrity", 86),
    ("Zhao Liying", "", "zhao liying|赵丽颖", "celebrity", 86),
    ("杨紫", "yang zi", "Yang Zi", "celebrity", 86),
    ("成毅", "cheng yi", "Cheng Yi", "celebrity", 84),
    ("任嘉伦", "ren jia lun", "Ren Jialun", "celebrity", 82),
    ("Ren Jialun", "", "ren jialun|任嘉伦", "celebrity", 82),
    ("李现", "li xian", "Li Xian", "celebrity", 84),
    ("Li Xian", "", "li xian|李现", "celebrity", 84),
    ("杨洋", "yang yang", "Yang Yang", "celebrity", 84),
    ("吴磊", "wu lei", "Wu Lei", "celebrity", 82),
    ("Wu Lei", "", "wu lei|吴磊", "celebrity", 82),
    ("胡歌", "hu ge", "Hu Ge", "celebrity", 86),
    ("Hu Ge", "", "hu ge|胡歌", "celebrity", 86),
    ("黄晓明", "huang xiao ming", "Huang Xiaoming", "celebrity", 82),
    ("Huang Xiaoming", "", "huang xiaoming|黄晓明", "celebrity", 82),
    ("陈坤", "chen kun", "Chen Kun", "celebrity", 80),
    ("章子怡", "zhang zi yi", "Zhang Ziyi", "celebrity", 82),
    ("Zhang Ziyi", "", "zhang ziyi|章子怡", "celebrity", 82),
    ("巩俐", "gong li", "Gong Li", "celebrity", 82),
    ("周迅", "zhou xun", "Zhou Xun", "celebrity", 82),
    ("汤唯", "tang wei", "Tang Wei", "celebrity", 80),
    ("舒淇", "shu qi", "Shu Qi", "celebrity", 80),
    ("黄渤", "huang bo", "Huang Bo", "celebrity", 86),
    ("Huang Bo", "", "huang bo|黄渤", "celebrity", 86),
    ("沈腾", "shen teng", "Shen Teng", "celebrity", 86),
    ("Shen Teng", "", "shen teng|沈腾", "celebrity", 86),
    ("贾玲", "jia ling", "Jia Ling", "celebrity", 84),
    ("Jia Ling", "", "jia ling|贾玲", "celebrity", 84),
    ("马丽", "ma li", "Ma Li", "celebrity", 80),
    ("张小斐", "zhang xiao fei", "Zhang Xiaofei", "celebrity", 80),
    ("吴京", "wu jing", "Wu Jing", "celebrity", 84),
    ("Wu Jing", "", "wu jing|吴京", "celebrity", 84),
    ("张译", "zhang yi yan", "Zhang Yi actor", "celebrity", 82),
    ("雷佳音", "lei jia yin", "Lei Jiayin", "celebrity", 80),
    ("孙俪", "sun li", "Sun Li", "celebrity", 82),
    ("靳东", "jin dong", "Jin Dong", "celebrity", 78),
    ("那英", "na ying", "Na Ying", "celebrity", 82),
    ("汪峰", "wang feng", "Wang Feng", "celebrity", 80),
    ("王菲", "wang fei", "Faye Wong", "celebrity", 84),
    ("张学友", "zhang xue you", "Jacky Cheung", "celebrity", 82),
    ("Jacky Cheung", "", "jacky cheung|张学友", "celebrity", 82),
    ("林俊杰", "lin jun jie", "JJ Lin", "celebrity", 84),
    ("JJ Lin", "", "jj lin|林俊杰", "celebrity", 84),
    ("蔡依林", "cai yi lin", "Jolin Tsai", "celebrity", 82),
    ("Jolin Tsai", "", "jolin tsai|蔡依林", "celebrity", 82),
    ("王力宏", "wang li hong", "Wang Leehom", "celebrity", 82),
    ("陈奕迅", "chen yi xun", "Eason Chan", "celebrity", 84),
    ("Eason Chan", "", "eason chan|陈奕迅", "celebrity", 84),
    ("毛不易", "mao bu yi", "Mao Buyi", "celebrity", 82),
    ("华晨宇", "hua chen yu", "Hua Chenyu", "celebrity", 80),
    ("时代少年团", "shi dai shao nian tuan", "TNT|Teens in Times", "celebrity", 80),
    ("TFBOYS", "", "tf boys|TF Boys", "celebrity", 82),
    ("蔡徐坤", "cai xu kun", "Cai Xukun", "celebrity", 82),
    ("Cai Xukun", "", "cai xukun|蔡徐坤", "celebrity", 82),
    ("黄子韬", "huang zi tao", "Huang Zitao", "celebrity", 80),
    ("Huang Zitao", "", "huang zitao|黄子韬", "celebrity", 80),
    ("BLACKPINK", "", "black pink|Black Pink", "celebrity", 84),
    ("Jennie", "", "blackpink jennie", "celebrity", 80),
    ("Jisoo", "", "blackpink jisoo", "celebrity", 78),
    ("Rosé", "", "blackpink rose|Rose", "celebrity", 78),
    ("BTS", "", "bts|防弹少年团", "celebrity", 84),
    ("防弹少年团", "fang dan shao nian tuan", "BTS", "celebrity", 84),
    ("NewJeans", "", "new jeans|New Jeans", "celebrity", 82),
    ("aespa", "", "aespa组合", "celebrity", 80),
    ("IVE", "", "ive组合", "celebrity", 78),
    ("Rihanna", "", "rihanna|蕾哈娜", "celebrity", 82),
    ("蕾哈娜", "lei ha na", "Rihanna", "celebrity", 80),
    ("Drake", "", "drake rapper", "celebrity", 82),
    ("Kanye West", "", "kanye west|Ye", "celebrity", 80),
    ("Kendrick Lamar", "", "kendrick lamar", "celebrity", 80),
    ("Billie Eilish", "", "billie eilish", "celebrity", 82),
    ("Ariana Grande", "", "ariana grande", "celebrity", 82),
    ("Lady Gaga", "", "lady gaga", "celebrity", 82),
    ("Tom Hanks", "", "tom hanks", "celebrity", 80),
    ("Leonardo DiCaprio", "", "leonardo dicaprio|小李子", "celebrity", 82),
    ("小李子", "xiao li zi", "Leonardo DiCaprio", "celebrity", 80),
    ("Brad Pitt", "", "brad pitt", "celebrity", 80),
    ("Angelina Jolie", "", "angelina jolie", "celebrity", 78),
    ("Jennifer Lawrence", "", "jennifer lawrence", "celebrity", 78),
    ("Scarlett Johansson", "", "scarlett johansson", "celebrity", 78),
    ("Robert Downey Jr", "", "robert downey jr|钢铁侠", "celebrity", 80),
    ("钢铁侠", "gang tie xia", "Iron Man|Robert Downey Jr", "celebrity", 78),
    ("漫威", "man wei", "Marvel", "tech_term", 80),
    ("Marvel", "", "marvel|漫威", "tech_term", 80),
    ("蝙蝠侠", "bian fu xia", "Batman", "celebrity", 76),
    ("Batman", "", "batman|蝙蝠侠", "celebrity", 76),
    # --- Athletes ---
    ("王楚钦", "wang chu qin", "Wang Chuqin", "athlete", 88),
    ("Wang Chuqin", "", "wang chuqin|王楚钦", "athlete", 88),
    ("孙颖莎", "sun ying sha", "Sun Yingsha", "athlete", 88),
    ("Sun Yingsha", "", "sun yingsha|孙颖莎", "athlete", 88),
    ("樊振东", "fan zhen dong", "Fan Zhendong", "athlete", 86),
    ("Fan Zhendong", "", "fan zhendong|樊振东", "athlete", 86),
    ("王曼昱", "wang man yu", "Wang Manyu", "athlete", 84),
    ("Wang Manyu", "", "wang manyu|王曼昱", "athlete", 84),
    ("郑钦文", "zheng qin wen", "Zheng Qinwen", "athlete", 86),
    ("Zheng Qinwen", "", "zheng qinwen|郑钦文", "athlete", 86),
    ("林诗栋", "lin shi dong", "Lin Shidong", "athlete", 80),
    ("马龙", "ma long", "Ma Long", "athlete", 86),
    ("Ma Long", "", "ma long|马龙", "athlete", 86),
    ("全红婵", "quan hong chan", "Quan Hongchan", "athlete", 86),
    ("Quan Hongchan", "", "quan hongchan|全红婵", "athlete", 86),
    ("蒯曼", "kuai man", "Kuai Man", "athlete", 76),
    ("林高远", "lin gao yuan", "Lin Gaoyuan", "athlete", 76),
    ("苏炳添", "su bing tian", "Su Bingtian", "athlete", 80),
    ("谷爱凌", "gu ai ling", "Eileen Gu", "athlete", 86),
    ("Eileen Gu", "", "eileen gu|谷爱凌", "athlete", 86),
    ("姚明", "yao ming", "Yao Ming", "athlete", 86),
    ("Yao Ming", "", "yao ming|姚明", "athlete", 86),
    ("李娜", "li na", "Li Na tennis", "athlete", 80),
    ("刘翔", "liu xiang", "Liu Xiang", "athlete", 80),
    ("易建联", "yi jian lian", "Yi Jianlian", "athlete", 78),
    ("C罗", "C luo", "Cristiano Ronaldo", "athlete", 86),
    ("Cristiano Ronaldo", "", "cristiano ronaldo|C罗", "athlete", 86),
    ("梅西", "mei xi", "Lionel Messi", "athlete", 88),
    ("Lionel Messi", "", "lionel messi|梅西", "athlete", 88),
    ("姆巴佩", "mu ba pei", "Kylian Mbappé", "athlete", 84),
    ("Kylian Mbappé", "", "kylian mbappe|姆巴佩", "athlete", 84),
    ("哈兰德", "ha lan de", "Erling Haaland", "athlete", 82),
    ("Erling Haaland", "", "erling haaland|哈兰德", "athlete", 82),
    ("詹姆斯", "zhan mu si", "LeBron James", "athlete", 86),
    ("LeBron James", "", "lebron james|詹姆斯", "athlete", 86),
    ("库里", "ku li", "Stephen Curry", "athlete", 84),
    ("Stephen Curry", "", "stephen curry|库里", "athlete", 84),
    ("科比", "ke bi", "Kobe Bryant", "athlete", 82),
    ("Kobe Bryant", "", "kobe bryant|科比", "athlete", 82),
    ("乔丹", "qiao dan", "Michael Jordan", "athlete", 84),
    ("Michael Jordan", "", "michael jordan|乔丹", "athlete", 84),
    ("费德勒", "fei de le", "Roger Federer", "athlete", 80),
    ("纳达尔", "na da er", "Rafael Nadal", "athlete", 80),
    ("德约科维奇", "de yue ke wei qi", "Novak Djokovic", "athlete", 82),
    ("Novak Djokovic", "", "novak djokovic|德约", "athlete", 82),
    # --- Consumer brands ---
    ("Burberry", "", "burberry|博柏利", "consumer_brand", 80),
    ("博柏利", "bo bai li", "Burberry", "consumer_brand", 80),
    ("Balenciaga", "", "balenciaga|巴黎世家", "consumer_brand", 82),
    ("巴黎世家", "ba li shi jia", "Balenciaga", "consumer_brand", 82),
    ("Versace", "", "versace|范思哲", "consumer_brand", 78),
    ("范思哲", "fan si zhe", "Versace", "consumer_brand", 78),
    ("Armani", "", "armani|阿玛尼", "consumer_brand", 80),
    ("阿玛尼", "a ma ni", "Armani", "consumer_brand", 80),
    ("Cartier", "", "cartier|卡地亚", "consumer_brand", 82),
    ("卡地亚", "ka di ya", "Cartier", "consumer_brand", 82),
    ("Bulgari", "", "bulgari|宝格丽", "consumer_brand", 78),
    ("宝格丽", "bao ge li", "Bulgari", "consumer_brand", 78),
    ("Van Cleef", "", "van cleef|梵克雅宝", "consumer_brand", 76),
    ("梵克雅宝", "fan ke ya bao", "Van Cleef", "consumer_brand", 76),
    ("Moncler", "", "moncler|盟可睐", "consumer_brand", 78),
    ("盟可睐", "meng ke lai", "Moncler", "consumer_brand", 78),
    ("Canada Goose", "", "canada goose|加拿大鹅", "consumer_brand", 78),
    ("加拿大鹅", "jia na da e", "Canada Goose", "consumer_brand", 78),
    ("New Balance", "", "new balance|新百伦", "consumer_brand", 80),
    ("新百伦", "xin bai lun", "New Balance", "consumer_brand", 80),
    ("Puma", "", "puma|彪马", "consumer_brand", 78),
    ("彪马", "biao ma", "Puma", "consumer_brand", 78),
    ("Converse", "", "converse|匡威", "consumer_brand", 76),
    ("匡威", "kuang wei", "Converse", "consumer_brand", 76),
    ("Vans", "", "vans", "consumer_brand", 76),
    ("Skechers", "", "skechers|斯凯奇", "consumer_brand", 76),
    ("斯凯奇", "si kai qi", "Skechers", "consumer_brand", 76),
    ("Levi's", "", "levis|李维斯", "consumer_brand", 76),
    ("李维斯", "li wei si", "Levi's", "consumer_brand", 76),
    ("Coach", "", "coach|蔻驰", "consumer_brand", 78),
    ("蔻驰", "kou chi", "Coach", "consumer_brand", 78),
    ("Michael Kors", "", "michael kors|MK", "consumer_brand", 76),
    ("Estée Lauder", "", "estee lauder|雅诗兰黛", "consumer_brand", 78),
    ("雅诗兰黛", "ya shi lan dai", "Estée Lauder", "consumer_brand", 78),
    ("L'Oréal", "", "loreal|欧莱雅", "consumer_brand", 78),
    ("欧莱雅", "ou lai ya", "L'Oréal", "consumer_brand", 78),
    ("Shiseido", "", "shiseido|资生堂", "consumer_brand", 76),
    ("资生堂", "zi sheng tang", "Shiseido", "consumer_brand", 76),
    ("SK-II", "", "sk two|SK2", "consumer_brand", 78),
    ("兰蔻", "lan ke", "Lancôme", "consumer_brand", 78),
    ("Lancôme", "", "lancome|兰蔻", "consumer_brand", 78),
    ("YSL", "", "ysl|圣罗兰", "consumer_brand", 78),
    ("圣罗兰", "sheng luo lan", "YSL", "consumer_brand", 78),
    ("MAC", "", "mac cosmetics", "consumer_brand", 76),
    ("完美日记", "wan mei ri ji", "Perfect Diary", "consumer_brand", 80),
    ("Perfect Diary", "", "perfect diary|完美日记", "consumer_brand", 80),
    ("花西子", "hua xi zi", "Florasis", "consumer_brand", 78),
    ("Florasis", "", "florasis|花西子", "consumer_brand", 78),
    ("名创优品", "ming chuang you pin", "Miniso", "consumer_brand", 78),
    ("Miniso", "", "miniso|名创优品", "consumer_brand", 78),
    ("海底捞", "hai di lao", "Haidilao", "consumer_brand", 82),
    ("Haidilao", "", "haidilao|海底捞", "consumer_brand", 82),
    ("西贝", "xi bei", "Xibei", "consumer_brand", 76),
    ("老乡鸡", "lao xiang ji", "Laoxiangji", "consumer_brand", 76),
    ("盒马", "he ma", "Hema|盒马鲜生", "consumer_brand", 80),
    ("Hema", "", "hema|盒马", "consumer_brand", 80),
    ("山姆会员店", "shan mu hui yuan dian", "Sam's Club", "consumer_brand", 80),
    ("Sam's Club", "", "sams club|山姆", "consumer_brand", 80),
    ("Costco", "", "costco|开市客", "consumer_brand", 80),
    ("开市客", "kai shi ke", "Costco", "consumer_brand", 80),
    ("沃尔玛", "wo er ma", "Walmart", "consumer_brand", 78),
    ("Walmart", "", "walmart|沃尔玛", "consumer_brand", 78),
    ("家乐福", "jia le fu", "Carrefour", "consumer_brand", 72),
    ("宜家", "yi jia", "IKEA", "consumer_brand", 80),
    ("IKEA", "", "ikea|宜家", "consumer_brand", 80),
    ("MUJI", "", "muji|无印良品", "consumer_brand", 78),
    ("无印良品", "wu yin liang pin", "MUJI", "consumer_brand", 78),
    ("始祖鸟", "shi zu niao", "Arc'teryx", "consumer_brand", 82),
    ("Arc'teryx", "", "arcteryx|始祖鸟", "consumer_brand", 82),
    ("北面", "bei mian", "The North Face", "consumer_brand", 78),
    ("The North Face", "", "north face|北面", "consumer_brand", 78),
    ("Columbia", "", "columbia sportswear", "consumer_brand", 72),
    ("李宁", "li ning", "Li-Ning", "consumer_brand", 82),
    ("Li-Ning", "", "li ning|李宁", "consumer_brand", 82),
    ("安踏", "an ta", "Anta", "consumer_brand", 82),
    ("Anta", "", "anta|安踏", "consumer_brand", 82),
    ("特步", "te bu", "Xtep", "consumer_brand", 76),
    ("Xtep", "", "xtep|特步", "consumer_brand", 76),
    ("鸿星尔克", "hong xing er ke", "Erke", "consumer_brand", 76),
    ("Erke", "", "erke|鸿星尔克", "consumer_brand", 76),
    ("波司登", "bo si deng", "Bosideng", "consumer_brand", 78),
    ("Bosideng", "", "bosideng|波司登", "consumer_brand", 78),
    ("周大福", "zhou da fu", "Chow Tai Fook", "consumer_brand", 76),
    ("Chow Tai Fook", "", "chow tai fook|周大福", "consumer_brand", 76),
    ("老凤祥", "lao feng xiang", "Lao Feng Xiang", "consumer_brand", 74),
    ("中国黄金", "zhong guo huang jin", "China Gold", "consumer_brand", 74),
    # --- Auto / EV ---
    ("领克", "ling ke", "Lynk & Co|Lynk", "tech_company", 84),
    ("Lynk & Co", "", "lynk co|领克", "tech_company", 84),
    ("问界", "wen jie", "AITO|AITO问界", "tech_company", 86),
    ("AITO", "", "aito|问界", "tech_company", 86),
    ("智界", "zhi jie", "Luxeed", "tech_company", 84),
    ("Luxeed", "", "luxeed|智界", "tech_company", 84),
    ("享界", "xiang jie", "Stelato", "tech_company", 82),
    ("Stelato", "", "stelato|享界", "tech_company", 82),
    ("尊界", "zun jie", "MAEXTRO", "tech_company", 82),
    ("MAEXTRO", "", "maextro|尊界", "tech_company", 82),
    ("小米YU7", "xiao mi YU7", "Xiaomi YU7|YU7", "tech_company", 88),
    ("YU7", "", "xiaomi yu7|小米YU7", "tech_company", 86),
    ("理想L9", "li xiang L9", "Li L9", "tech_company", 82),
    ("Li L9", "", "li l9|理想L9", "tech_company", 82),
    ("理想MEGA", "li xiang MEGA", "Li MEGA|MEGA", "tech_company", 82),
    ("小鹏MONA", "xiao peng MONA", "MONA", "tech_company", 80),
    ("极狐", "ji hu", "ARCFOX", "tech_company", 80),
    ("ARCFOX", "", "arcfox|极狐", "tech_company", 80),
    ("阿维塔", "a wei ta", "Avatr", "tech_company", 82),
    ("Avatr", "", "avatr|阿维塔", "tech_company", 82),
    ("深蓝", "shen lan", "Deepal", "tech_company", 80),
    ("Deepal", "", "deepal|深蓝", "tech_company", 80),
    ("岚图", "lan tu", "Voyah", "tech_company", 82),
    ("Voyah", "", "voyah|岚图", "tech_company", 82),
    ("腾势", "teng shi", "Denza", "tech_company", 82),
    ("Denza", "", "denza|腾势", "tech_company", 82),
    ("方程豹", "fang cheng bao", "Fangchengbao", "tech_company", 82),
    ("Fangchengbao", "", "fangchengbao|方程豹", "tech_company", 82),
    ("仰望", "yang wang", "Yangwang", "tech_company", 84),
    ("Yangwang", "", "yangwang|仰望", "tech_company", 84),
    ("智己", "zhi ji", "IM Motors", "tech_company", 82),
    ("IM Motors", "", "im motors|智己", "tech_company", 82),
    ("飞凡", "fei fan", "Rising Auto", "tech_company", 76),
    ("昊铂", "hao bo", "Hyper", "tech_company", 78),
    ("Hyper", "", "hyper|昊铂", "tech_company", 78),
    ("广汽埃安", "guang qi ai an", "Aion", "tech_company", 82),
    ("Aion", "", "aion|埃安", "tech_company", 82),
    ("哪吒汽车", "na zha qi che", "Neta Auto", "tech_company", 80),
    ("Neta Auto", "", "neta auto|哪吒汽车", "tech_company", 80),
    ("零跑", "ling pao", "Leapmotor", "tech_company", 84),
    ("Leapmotor", "", "leapmotor|零跑", "tech_company", 84),
    ("赛力斯", "sai li si", "Seres", "tech_company", 84),
    ("Seres", "", "seres|赛力斯", "tech_company", 84),
    ("长安", "chang an", "Changan", "tech_company", 78),
    ("Changan", "", "changan|长安", "tech_company", 78),
    ("上汽", "shang qi", "SAIC", "tech_company", 78),
    ("SAIC", "", "saic|上汽", "tech_company", 78),
    ("一汽", "yi qi", "FAW", "tech_company", 76),
    ("FAW", "", "faw|一汽", "tech_company", 76),
    ("东风", "dong feng", "Dongfeng", "tech_company", 76),
    ("Dongfeng", "", "dongfeng|东风", "tech_company", 76),
    ("奇瑞", "qi rui", "Chery", "tech_company", 78),
    ("Chery", "", "chery|奇瑞", "tech_company", 78),
    ("吉利银河", "ji li yin he", "Galaxy Geely", "tech_company", 78),
    ("路特斯", "lu te si", "Lotus", "tech_company", 80),
    ("Lotus", "", "lotus|路特斯", "tech_company", 80),
    ("保时捷", "bao shi jie", "Porsche", "tech_company", 84),
    ("Porsche", "", "porsche|保时捷", "tech_company", 84),
    ("法拉利", "fa la li", "Ferrari", "tech_company", 82),
    ("Ferrari", "", "ferrari|法拉利", "tech_company", 82),
    ("兰博基尼", "lan bo ji ni", "Lamborghini", "tech_company", 82),
    ("Lamborghini", "", "lamborghini|兰博基尼", "tech_company", 82),
    ("奔驰", "ben chi", "Mercedes-Benz", "tech_company", 84),
    ("Mercedes-Benz", "", "mercedes benz|奔驰", "tech_company", 84),
    ("宝马", "bao ma", "BMW", "tech_company", 84),
    ("BMW", "", "bmw|宝马", "tech_company", 84),
    ("大众", "da zhong", "Volkswagen", "tech_company", 80),
    ("Volkswagen", "", "volkswagen|大众", "tech_company", 80),
    ("丰田", "feng tian", "Toyota", "tech_company", 80),
    ("Toyota", "", "toyota|丰田", "tech_company", 80),
    ("本田", "ben tian", "Honda", "tech_company", 78),
    ("Honda", "", "honda|本田", "tech_company", 78),
    # --- Tech / semicon / cloud ---
    ("Anduril", "", "anduril industries", "tech_company", 80),
    ("Scale AI", "", "scale ai|Scale", "tech_company", 84),
    ("Labelbox", "", "labelbox", "tech_company", 74),
    ("Weights & Biases", "", "weights and biases|W&B", "dev_tool", 80),
    ("W&B", "", "weights and biases", "dev_tool", 78),
    ("Langfuse", "", "langfuse", "dev_tool", 78),
    ("Helicone", "", "helicone", "dev_tool", 74),
    ("Braintrust", "", "braintrust ai", "dev_tool", 76),
    ("Arize", "", "arize ai|Arize AI", "dev_tool", 74),
    ("CoreWeave", "", "coreweave", "tech_company", 82),
    ("Lambda Labs", "", "lambda labs|Lambda", "tech_company", 78),
    ("Crusoe", "", "crusoe energy", "tech_company", 74),
    ("RunPod", "", "run pod|RunPod", "tech_company", 78),
    ("Groq Cloud", "", "groq cloud", "ai_platform", 78),
    ("Baseten", "", "baseten", "ai_platform", 76),
    ("Anyscale", "", "anyscale|Ray", "tech_company", 78),
    ("Ray Serve", "", "ray serve", "dev_tool", 76),
    ("Micron", "", "micron|美光", "tech_company", 82),
    ("美光", "mei guang", "Micron", "tech_company", 82),
    ("SK Hynix", "", "sk hynix|海力士", "tech_company", 82),
    ("海力士", "hai li shi", "SK Hynix", "tech_company", 82),
    ("Kioxia", "", "kioxia|铠侠", "tech_company", 76),
    ("铠侠", "kai xia", "Kioxia", "tech_company", 76),
    ("Western Digital", "", "western digital|西部数据", "tech_company", 78),
    ("西部数据", "xi bu shu ju", "Western Digital", "tech_company", 78),
    ("MediaTek", "", "mediatek|联发科", "tech_company", 82),
    ("联发科", "lian fa ke", "MediaTek", "tech_company", 82),
    ("Rockchip", "", "rockchip|瑞芯微", "tech_company", 78),
    ("瑞芯微", "rui xin wei", "Rockchip", "tech_company", 78),
    ("Allwinner", "", "allwinner|全志", "tech_company", 74),
    ("全志", "quan zhi", "Allwinner", "tech_company", 74),
    ("寒武纪", "han wu ji", "Cambricon", "tech_company", 80),
    ("Cambricon", "", "cambricon|寒武纪", "tech_company", 80),
    ("壁仞", "bi ren", "Biren", "tech_company", 78),
    ("Biren", "", "biren|壁仞", "tech_company", 78),
    ("摩尔线程", "mo er xian cheng", "Moore Threads", "tech_company", 80),
    ("Moore Threads", "", "moore threads|摩尔线程", "tech_company", 80),
    ("燧原", "sui yuan", "Enflame", "tech_company", 76),
    ("Enflame", "", "enflame|燧原", "tech_company", 76),
    ("平头哥", "ping tou ge", "T-Head", "tech_company", 78),
    ("T-Head", "", "t head|平头哥", "tech_company", 78),
    ("紫光", "zi guang", "Unigroup", "tech_company", 76),
    ("Unigroup", "", "unigroup|紫光", "tech_company", 76),
    ("长鑫", "chang xin", "CXMT", "tech_company", 78),
    ("CXMT", "", "cxmt|长鑫存储", "tech_company", 78),
    ("长江存储", "chang jiang cun chu", "YMTC", "tech_company", 80),
    ("YMTC", "", "ymtc|长江存储", "tech_company", 80),
    ("商汤绝影", "shang tang jue ying", "SenseAuto", "tech_company", 78),
    ("绝影", "jue ying", "SenseAuto", "tech_company", 76),
    ("Momenta", "", "momenta|魔门塔", "tech_company", 82),
    ("魔门塔", "mo men ta", "Momenta", "tech_company", 80),
    ("文远知行", "wen yuan zhi xing", "WeRide", "tech_company", 82),
    ("WeRide", "", "weride|文远知行", "tech_company", 82),
    ("小马智行", "xiao ma zhi xing", "Pony.ai", "tech_company", 82),
    ("Pony.ai", "", "pony ai|小马智行", "tech_company", 82),
    ("元戎启行", "yuan rong qi xing", "DeepRoute", "tech_company", 78),
    ("DeepRoute", "", "deeproute|元戎启行", "tech_company", 78),
    ("禾赛", "he sai", "Hesai", "tech_company", 80),
    ("Hesai", "", "hesai|禾赛", "tech_company", 80),
    ("速腾聚创", "su teng ju chuang", "RoboSense", "tech_company", 80),
    ("RoboSense", "", "robosense|速腾聚创", "tech_company", 80),
    ("图达通", "tu da tong", "Innovusion", "tech_company", 76),
    ("Innovusion", "", "innovusion|图达通", "tech_company", 76),
    ("OpenHarmony", "", "open harmony|开源鸿蒙", "tech_company", 82),
    ("开源鸿蒙", "kai yuan hong meng", "OpenHarmony", "tech_company", 82),
    ("openEuler", "", "open euler|欧拉", "tech_company", 76),
    ("欧拉", "ou la", "openEuler", "tech_company", 76),
    ("龙芯", "long xin", "Loongson", "tech_company", 78),
    ("Loongson", "", "loongson|龙芯", "tech_company", 78),
    ("飞腾", "fei teng", "Phytium", "tech_company", 76),
    ("Phytium", "", "phytium|飞腾", "tech_company", 76),
    ("鲲鹏", "kun peng", "Kunpeng", "tech_company", 80),
    ("Kunpeng", "", "kunpeng|鲲鹏", "tech_company", 80),
    ("飞书", "fei shu", "Lark", "tech_company", 86),
    ("Lark", "", "lark|飞书", "tech_company", 86),
    ("钉钉", "ding ding", "DingTalk", "tech_company", 84),
    ("DingTalk", "", "dingtalk|钉钉", "tech_company", 84),
    ("企业微信", "qi ye wei xin", "WeCom", "tech_company", 84),
    ("WeCom", "", "wecom|企业微信", "tech_company", 84),
    # --- AI / internet hot terms ---
    ("skill", "", "skills|Agent Skills", "ai_term", 78),
    ("skills", "", "agent skills|Claude Skills", "ai_term", 76),
    ("Agent Skills", "", "agent skills|Claude Skills", "ai_term", 82),
    ("Claude Skills", "", "claude skills", "ai_term", 80),
    ("MCP协议", "MCP xie yi", "MCP protocol", "ai_term", 84),
    ("A2A", "", "agent to agent|Agent2Agent", "ai_term", 82),
    ("Agent2Agent", "", "a2a|agent to agent", "ai_term", 80),
    ("A2A协议", "A2A xie yi", "Agent2Agent", "ai_term", 78),
    ("deep agent", "", "deep agents", "ai_term", 82),
    ("deep agents", "", "deep agent", "ai_term", 80),
    ("agentic workflow", "", "agentic workflows", "ai_term", 84),
    ("agentic coding", "", "agentic code", "ai_term", 82),
    ("spec driven", "", "spec-driven|规格驱动", "ai_term", 80),
    ("spec-driven", "", "spec driven", "ai_term", 80),
    ("规格驱动", "gui ge qu dong", "spec-driven", "ai_term", 78),
    ("vibe marketing", "", "氛围营销", "ai_term", 76),
    ("氛围营销", "fen wei ying xiao", "vibe marketing", "ai_term", 74),
    ("AI原生应用", "AI yuan sheng ying yong", "AI native app", "ai_term", 80),
    ("AI应用", "AI ying yong", "AI app", "ai_term", 78),
    ("模型蒸馏", "mo xing zheng liu", "model distillation", "ai_term", 80),
    ("model distillation", "", "模型蒸馏", "ai_term", 78),
    ("合成数据", "he cheng shu ju", "synthetic data", "ai_term", 80),
    ("synthetic data", "", "合成数据", "ai_term", 78),
    ("数据飞轮", "shu ju fei lun", "data flywheel", "ai_term", 78),
    ("data flywheel", "", "数据飞轮", "ai_term", 76),
    ("长上下文", "chang shang xia wen", "long context", "ai_term", 82),
    ("long context", "", "长上下文", "ai_term", 80),
    ("百万上下文", "bai wan shang xia wen", "million context", "ai_term", 80),
    ("million context", "", "百万上下文", "ai_term", 78),
    ("KV cache", "", "kv cache|KV缓存", "ai_term", 80),
    ("KV缓存", "KV huan cun", "KV cache", "ai_term", 78),
    ("投机解码", "tou ji jie ma", "speculative decoding", "ai_term", 76),
    ("speculative decoding", "", "投机解码", "ai_term", 74),
    ("MoE路由", "MoE lu you", "expert routing", "ai_term", 76),
    ("expert routing", "", "MoE路由", "ai_term", 74),
    ("稀疏注意力", "xi shu zhu yi li", "sparse attention", "ai_term", 74),
    ("sparse attention", "", "稀疏注意力", "ai_term", 72),
    ("视频大模型", "shi pin da mo xing", "video foundation model", "ai_term", 82),
    ("video foundation model", "", "视频大模型", "ai_term", 80),
    ("多智能体协作", "duo zhi neng ti xie zuo", "multi-agent collaboration", "ai_term", 80),
    ("AI陪伴", "AI pei ban", "AI companion", "ai_term", 78),
    ("AI companion", "", "AI陪伴", "ai_term", 76),
    ("数字人", "shu zi ren", "digital human", "ai_term", 82),
    ("digital human", "", "数字人", "ai_term", 80),
    ("虚拟偶像", "xu ni ou xiang", "virtual idol", "ai_term", 76),
    ("virtual idol", "", "虚拟偶像", "ai_term", 74),
    ("赛博永生", "sai bo yong sheng", "cyber immortality", "tech_term", 72),
    ("赛博菩萨", "sai bo pu sa", "cyber bodhisattva", "tech_term", 70),
    ("赛博佛祖", "sai bo fo zu", "cyber buddha", "tech_term", 70),
    ("抽象", "chou xiang", "abstract meme", "tech_term", 72),
    ("钝感力", "dun gan li", "emotional bluntness", "tech_term", 74),
    ("松弛感", "song chi gan", "relaxed vibe", "tech_term", 76),
    ("情绪稳定", "qing xu wen ding", "emotionally stable", "tech_term", 74),
    ("搭子", "da zi", "buddy partner", "tech_term", 76),
    ("citywalk", "", "city walk|City Walk", "tech_term", 76),
    ("City Walk", "", "citywalk", "tech_term", 74),
    ("特种兵旅游", "te zhong bing lv you", "special forces travel", "tech_term", 72),
    ("显眼包", "xian yan bao", "attention seeker", "tech_term", 72),
    ("i人", "i ren", "introvert", "tech_term", 74),
    ("e人", "e ren", "extrovert", "tech_term", 74),
    ("MBTI", "", "mbti人格", "tech_term", 76),
    ("脆皮大学生", "cui pi da xue sheng", "fragile college student", "tech_term", 70),
    ("班味", "ban wei", "office vibe", "tech_term", 74),
    ("班味很重", "ban wei hen zhong", "heavy office vibe", "tech_term", 72),
    ("偷感", "tou gan", "stealth vibe", "tech_term", 72),
    ("偷感很重", "tou gan hen zhong", "heavy stealth vibe", "tech_term", 70),
    ("水灵灵", "shui ling ling", "fresh and lively", "tech_term", 70),
    ("硬控", "ying kong", "hard control meme", "tech_term", 72),
    ("绝绝子", "jue jue zi", "absolutely amazing", "tech_term", 72),
    ("尊嘟假嘟", "zun du jia du", "really or not", "tech_term", 70),
    ("芭比Q了", "ba bi Q le", "barbecue done|finished", "tech_term", 68),
    ("栓Q", "shuan Q", "thank you meme", "tech_term", 68),
    ("YYDS", "", "yyds|永远的神", "tech_term", 74),
    ("永远的神", "yong yuan de shen", "YYDS", "tech_term", 72),
    ("破防", "po fang", "emotionally broken", "tech_term", 74),
    ("上头", "shang tou", "addictive hype", "tech_term", 70),
    ("下头", "xia tou", "turn off vibe", "tech_term", 70),
    ("拿捏", "na nie", "nailed it", "tech_term", 70),
    ("种草", "zhong cao", "plant grass recommend", "tech_term", 78),
    ("拔草", "ba cao", "unrecommend", "tech_term", 74),
    ("安利", "an li", "recommend", "tech_term", 74),
    ("避雷", "bi lei", "avoid pitfall", "tech_term", 74),
    ("测评", "ce ping", "product review", "tech_term", 76),
    ("开箱", "kai xiang", "unboxing", "tech_term", 76),
    ("沉浸式", "chen jin shi", "immersive", "tech_term", 74),
    ("氛围感", "fen wei gan", "atmospheric vibe", "tech_term", 76),
    ("高级感", "gao ji gan", "premium feel", "tech_term", 74),
    ("质感", "zhi gan", "texture quality", "tech_term", 72),
    ("带货", "dai huo", "live commerce sales", "tech_term", 78),
    ("直播带货", "zhi bo dai huo", "livestream commerce", "tech_term", 80),
    ("短视频", "duan shi pin", "short video", "tech_term", 78),
    ("中视频", "zhong shi pin", "mid-length video", "tech_term", 72),
    ("知识付费", "zhi shi fu fei", "paid knowledge", "tech_term", 74),
    ("私域", "si yu", "private domain traffic", "tech_term", 78),
    ("公域", "gong yu", "public domain traffic", "tech_term", 74),
    ("全域经营", "quan yu jing ying", "omnichannel operation", "tech_term", 74),
    ("本地化", "ben di hua", "localization", "tech_term", 72),
    ("GTM", "", "go to market", "tech_term", 74),
    ("PLG", "", "product led growth", "tech_term", 72),
    ("SLG", "", "sales led growth", "tech_term", 70),
    ("ARR", "", "annual recurring revenue", "tech_term", 72),
    ("MRR", "", "monthly recurring revenue", "tech_term", 70),
    ("NDR", "", "net dollar retention", "tech_term", 68),
    ("CAC", "", "customer acquisition cost", "tech_term", 70),
    ("LTV", "", "lifetime value", "tech_term", 70),
    ("融资", "rong zi", "fundraising", "tech_term", 74),
    ("估值", "gu zhi", "valuation", "tech_term", 74),
    ("IPO", "", "initial public offering|上市", "tech_term", 76),
    ("上市", "shang shi", "IPO listing", "tech_term", 74),
    ("独角兽", "du jiao shou", "unicorn startup", "tech_term", 76),
    ("decacorn", "", "decacorn startup", "tech_term", 68),
    ("A轮", "A lun", "Series A", "tech_term", 72),
    ("B轮", "B lun", "Series B", "tech_term", 70),
    ("C轮", "C lun", "Series C", "tech_term", 68),
    ("Pre-A", "", "pre a round", "tech_term", 68),
    ("降本增效", "jiang ben zeng xiao", "cost cut efficiency", "tech_term", 78),
    ("裁员", "cai yuan", "layoffs", "tech_term", 74),
    ("优化", "you hua", "layoff euphemism", "tech_term", 70),
    ("毕业", "bi ye", "layoff euphemism", "tech_term", 68),
    ("35岁危机", "35 sui wei ji", "age 35 crisis", "tech_term", 72),
    ("考公", "kao gong", "civil service exam", "tech_term", 74),
    ("考编", "kao bian", "public institution exam", "tech_term", 72),
    ("灵活就业", "ling huo jiu ye", "flexible employment", "tech_term", 70),
    ("银发经济", "yin fa jing ji", "silver economy", "tech_term", 78),
    ("宠物经济", "chong wu jing ji", "pet economy", "tech_term", 74),
    ("悦己消费", "yue ji xiao fei", "self-reward spending", "tech_term", 74),
    ("情绪消费", "qing xu xiao fei", "emotional spending", "tech_term", 74),
    ("体验经济", "ti yan jing ji", "experience economy", "tech_term", 72),
    ("首发经济", "shou fa jing ji", "launch economy", "tech_term", 74),
    ("冰雪经济", "bing xue jing ji", "ice snow economy", "tech_term", 72),
    ("以旧换新", "yi jiu huan xin", "trade-in program", "tech_term", 78),
    ("国补", "guo bu", "national subsidy", "tech_term", 80),
    ("消费券", "xiao fei quan", "consumption voucher", "tech_term", 72),
    ("数据要素", "shu ju yao su", "data as factor", "tech_term", 78),
    ("数据资产", "shu ju zi chan", "data assets", "tech_term", 76),
    ("数据确权", "shu ju que quan", "data rights confirmation", "tech_term", 74),
    ("耐心资本", "nai xin zi ben", "patient capital", "tech_term", 76),
    ("长期主义", "chang qi zhu yi", "long-termism", "tech_term", 76),
    ("价值投资者", "jia zhi tou zi zhe", "value investor", "tech_term", 72),
    ("价值投资", "jia zhi tou zi", "value investing", "tech_term", 72),
    # --- Games / media IP ---
    ("米哈游", "mi ha you", "miHoYo", "game_ip", 86),
    ("miHoYo", "", "mihoyo|米哈游", "game_ip", 86),
    ("原神", "yuan shen", "Genshin Impact", "game_ip", 88),
    ("Genshin Impact", "", "genshin impact|原神", "game_ip", 88),
    ("崩坏星穹铁道", "beng huai xing qiong tie dao", "Honkai Star Rail", "game_ip", 86),
    ("Honkai Star Rail", "", "honkai star rail|星穹铁道", "game_ip", 86),
    ("星穹铁道", "xing qiong tie dao", "Honkai Star Rail", "game_ip", 84),
    ("崩坏", "beng huai", "Honkai", "game_ip", 80),
    ("Honkai", "", "honkai|崩坏", "game_ip", 80),
    ("绝区零", "jue qu ling", "Zenless Zone Zero", "game_ip", 84),
    ("Zenless Zone Zero", "", "zenless zone zero|ZZZ", "game_ip", 84),
    ("鸣潮", "ming chao", "Wuthering Waves", "game_ip", 82),
    ("Wuthering Waves", "", "wuthering waves|鸣潮", "game_ip", 82),
    ("腾讯游戏", "teng xun you xi", "Tencent Games", "game_ip", 84),
    ("王者荣耀", "wang zhe rong yao", "Honor of Kings", "game_ip", 88),
    ("Honor of Kings", "", "honor of kings|王者", "game_ip", 88),
    ("和平精英", "he ping jing ying", "PUBG Mobile China", "game_ip", 86),
    ("PUBG Mobile", "", "pubg mobile|和平精英", "game_ip", 84),
    ("英雄联盟", "ying xiong lian meng", "League of Legends", "game_ip", 86),
    ("League of Legends", "", "league of legends|LOL", "game_ip", 86),
    ("无畏契约", "wu wei qi yue", "Valorant", "game_ip", 84),
    ("Valorant", "", "valorant|无畏契约", "game_ip", 84),
    ("DOTA2", "", "dota 2|Dota 2", "game_ip", 82),
    ("Dota 2", "", "dota2|DOTA2", "game_ip", 82),
    ("CS2", "", "counter strike 2|CSGO", "game_ip", 82),
    ("Counter-Strike", "", "counter strike|CS2", "game_ip", 80),
    ("Steam", "", "steam平台", "game_ip", 86),
    ("Epic Games", "", "epic games|Epic", "game_ip", 80),
    ("育碧", "yu bi", "Ubisoft", "game_ip", 78),
    ("Ubisoft", "", "ubisoft|育碧", "game_ip", 78),
    ("暴雪", "bao xue", "Blizzard", "game_ip", 82),
    ("Blizzard", "", "blizzard|暴雪", "game_ip", 82),
    ("动视", "dong shi", "Activision", "game_ip", 80),
    ("Activision", "", "activision|动视", "game_ip", 80),
    ("PlayStation", "", "playstation|PS5", "game_ip", 82),
    ("PS5", "", "playstation 5", "game_ip", 80),
    ("Xbox", "", "xbox series", "game_ip", 80),
    ("艾尔登法环", "ai er deng fa huan", "Elden Ring", "game_ip", 82),
    ("Elden Ring", "", "elden ring|老头环", "game_ip", 82),
    ("老头环", "lao tou huan", "Elden Ring", "game_ip", 80),
    ("何同学", "he tong xue", "何同学UP主", "celebrity", 82),
    ("老师好我叫何同学", "lao shi hao wo jiao he tong xue", "何同学", "celebrity", 80),
    ("罗翔", "luo xiang", "罗翔说刑法", "celebrity", 84),
    ("罗翔说刑法", "luo xiang shuo xing fa", "罗翔", "celebrity", 82),
    ("papi酱", "papi jiang", "papi", "celebrity", 78),
    ("李子柒", "li zi qi", "Li Ziqi", "celebrity", 84),
    ("Li Ziqi", "", "li ziqi|李子柒", "celebrity", 84),
    ("董宇辉", "dong yu hui", "Dong Yuhui", "celebrity", 84),
    ("Dong Yuhui", "", "dong yuhui|董宇辉", "celebrity", 84),
    ("东方甄选", "dong fang zhen xuan", "East Buy", "tech_company", 80),
    ("疯狂小杨哥", "feng kuang xiao yang ge", "Xiao Yangge", "celebrity", 78),
    ("李佳琦", "li jia qi", "Austin Li", "celebrity", 84),
    ("Austin Li", "", "austin li|李佳琦", "celebrity", 84),
    ("薇娅", "wei ya", "Viya", "celebrity", 76),
    ("Viya", "", "viya|薇娅", "celebrity", 76),
    ("交个朋友", "jiao ge peng you", "Make Friends Live", "tech_company", 78),
    ("交个朋友直播间", "jiao ge peng you zhi bo jian", "交个朋友", "tech_term", 76),
    # --- Finance / investment ---
    ("伯克希尔", "bo ke xi er", "Berkshire Hathaway", "fintech", 82),
    ("Berkshire Hathaway", "", "berkshire hathaway|伯克希尔", "fintech", 82),
    ("芒格", "mang ge", "Charlie Munger", "tech_leader", 80),
    ("Charlie Munger", "", "charlie munger|芒格", "tech_leader", 80),
    ("索罗斯", "suo luo si", "George Soros", "tech_leader", 78),
    ("George Soros", "", "george soros|索罗斯", "tech_leader", 78),
    ("达利欧", "da li ou", "Ray Dalio", "tech_leader", 80),
    ("Ray Dalio", "", "ray dalio|达利欧", "tech_leader", 80),
    ("桥水", "qiao shui", "Bridgewater", "fintech", 80),
    ("Bridgewater", "", "bridgewater|桥水基金", "fintech", 80),
    ("黑石", "hei shi", "Blackstone", "fintech", 80),
    ("Blackstone", "", "blackstone|黑石集团", "fintech", 80),
    ("KKR", "", "kkr", "fintech", 76),
    ("红杉", "hong shan", "Sequoia", "fintech", 80),
    ("Sequoia", "", "sequoia|红杉资本", "fintech", 80),
    ("a16z", "", "andreessen horowitz|A16Z", "fintech", 82),
    ("Andreessen Horowitz", "", "a16z|andreessen horowitz", "fintech", 82),
    ("高瓴", "gao ling", "Hillhouse", "fintech", 80),
    ("Hillhouse", "", "hillhouse|高瓴资本", "fintech", 80),
    ("IDG", "", "idg capital", "fintech", 76),
    ("经纬", "jing wei", "Matrix Partners China", "fintech", 76),
    ("Matrix Partners", "", "matrix partners|经纬创投", "fintech", 76),
    ("真格", "zhen ge", "ZhenFund", "fintech", 76),
    ("ZhenFund", "", "zhen fund|真格基金", "fintech", 76),
    ("源码", "yuan ma", "Source Code Capital", "fintech", 74),
    ("中金", "zhong jin", "CICC", "fintech", 78),
    ("CICC", "", "cicc|中金公司", "fintech", 78),
    ("中信", "zhong xin", "CITIC", "fintech", 78),
    ("CITIC", "", "citic|中信证券", "fintech", 78),
    ("华泰", "hua tai", "Huatai", "fintech", 76),
    ("Huatai", "", "huatai|华泰证券", "fintech", 76),
    ("国泰君安", "guo tai jun an", "Guotai Junan", "fintech", 76),
    ("Guotai Junan", "", "guotai junan|国泰君安", "fintech", 76),
    ("摩根大通", "mo gen da tong", "JPMorgan", "fintech", 80),
    ("JPMorgan", "", "jp morgan|摩根大通", "fintech", 80),
    ("高盛", "gao sheng", "Goldman Sachs", "fintech", 82),
    ("Goldman Sachs", "", "goldman sachs|高盛", "fintech", 82),
    ("摩根士丹利", "mo gen shi dan li", "Morgan Stanley", "fintech", 80),
    ("Morgan Stanley", "", "morgan stanley|摩根士丹利", "fintech", 80),
    ("纳斯达克", "na si da ke", "Nasdaq", "fintech", 80),
    ("Nasdaq", "", "nasdaq|纳斯达克", "fintech", 80),
    ("标普500", "biao pu 500", "S&P 500", "fintech", 78),
    ("S&P 500", "", "s and p 500|标普500", "fintech", 78),
    ("道琼斯", "dao qiong si", "Dow Jones", "fintech", 76),
    ("Dow Jones", "", "dow jones|道琼斯", "fintech", 76),
    ("恒生指数", "heng sheng zhi shu", "Hang Seng Index", "fintech", 76),
    ("沪深300", "hu shen 300", "CSI 300", "fintech", 76),
    ("比特币", "bi te bi", "Bitcoin", "fintech", 84),
    ("Bitcoin", "", "bitcoin|BTC", "fintech", 84),
    ("BTC", "", "bitcoin|比特币", "fintech", 80),
    ("以太坊", "yi tai fang", "Ethereum", "fintech", 82),
    ("Ethereum", "", "ethereum|ETH", "fintech", 82),
    ("ETH", "", "ethereum|以太坊", "fintech", 78),
    ("Solana", "", "solana crypto", "fintech", 78),
    ("狗狗币", "gou gou bi", "Dogecoin", "fintech", 76),
    ("Dogecoin", "", "dogecoin|狗狗币", "fintech", 76),
    ("美联储", "mei lian chu", "Federal Reserve", "fintech", 82),
    ("Federal Reserve", "", "federal reserve|美联储", "fintech", 82),
    ("鲍威尔", "bao wei er", "Jerome Powell", "tech_leader", 80),
    ("Jerome Powell", "", "jerome powell|鲍威尔", "tech_leader", 80),
    ("加息", "jia xi", "rate hike", "fintech", 74),
    ("降息", "jiang xi", "rate cut", "fintech", 76),
    ("量化宽松", "liang hua kuan song", "quantitative easing", "fintech", 74),
]


def load_existing_terms(seed_path: Path) -> set[str]:
    terms: set[str] = set()
    with seed_path.open(encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if not parts:
                continue
            word = parts[0].strip()
            if word:
                terms.add(word.lower())
            if len(parts) > 2:
                for alias in parts[2].split("|"):
                    alias = alias.strip()
                    if alias:
                        terms.add(alias.lower())
    return terms


def format_row(word: str, pinyin: str, aliases: str, category: str, weight: int) -> str:
    return f"{word}\t{pinyin}\t{aliases}\t{category}\t{weight}"


def main() -> int:
    existing = load_existing_terms(SEED_PATH)
    seen_in_batch: set[str] = set()
    to_append: list[str] = []
    skipped: list[str] = []

    for word, pinyin, aliases, category, weight in EXPANSION:
        key = word.strip().lower()
        if not key:
            continue
        if key in existing or key in seen_in_batch:
            skipped.append(word)
            continue
        seen_in_batch.add(key)
        to_append.append(format_row(word, pinyin, aliases, category, weight))

    original = SEED_PATH.read_text(encoding="utf-8")
    if not original.endswith("\n"):
        original += "\n"

    block = [
        "",
        "# --- Batch 2 expansion (2026-07-06): AI, celebrities, brands, hot terms ---",
        *to_append,
        "",
    ]
    SEED_PATH.write_text(original + "\n".join(block), encoding="utf-8")

    print(f"Appended: {len(to_append)} rows")
    print(f"Skipped duplicates: {len(skipped)}")
    if skipped:
        preview = ", ".join(skipped[:40])
        suffix = "..." if len(skipped) > 40 else ""
        print(f"Skipped preview: {preview}{suffix}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
